# ~/.config/just/justfile

global := env_var("HOME") / ".config/just/justfile"

default:
    @just --justfile {{global}} --working-directory ~ --list


# Shortcuts

config:
    nvim ~/.config/just/justfile

nvim:
    cd ~/.config/nvim && yazi .

yazi:
    cd ~/.config/yazi && yazi .

hypr:
    cd ~/.config/hypr && yazi .

ssh:
    cd ~/.ssh && yazi .

# System

update:
    topgrade

arch-news:
    arch_news_check

orphans:
    paru -Qtdq

orphans-remove:
    paru -Qtdq | paru -Rns -

clean:
    sudo pacman -Sc

# Hyprland / Waybar

waybar-reload:
    pkill waybar || true
    waybar & disown

swaync-reload:
    swaync-client -R
    swaync-client -rs

reload:
    hyprctl reload

# Diagnostics

ip:
    ip -brief addr

ports:
    ss -tulpn

disk:
    dust ~

journal:
    journalctl -p 3 -xb

failed:
    systemctl --failed

# Dot file management

stow name:
    stow -t ~ {{name}}

unstow name:
    stow -D -t ~ {{name}}

dots:
    cd ~/dotfiles/home/ && yazi .

zsh:
    cd ~ && nvim ./.zshrc

# Search

todo:
    @result="$(rg --line-number --column --no-heading 'TODO|FIXME|HACK' ~/Development | \
      fzf --delimiter ':' \
          --preview 'bat --style=numbers --color=always --highlight-line {2} {1}' \
          --preview-window=right:60%)"; \
    [ -z "$result" ] && exit 0; \
    file="$(echo "$result" | cut -d: -f1)"; \
    line="$(echo "$result" | cut -d: -f2)"; \
    nvim "+$line" "$file"

repos:
    @dir="$(fd -H '^\.git$' ~/Development -t d | sed 's|/.git$||' | fzf)"; \
    [ -z "$dir" ] && exit 0; \
    yazi "$dir"

# Backups

backup-docs:
    rclone sync ~/Documents remote:Documents
