-- home/hypr/.config/hypr/theme/generate/rofi.lua

local HOME = os.getenv("HOME")
local Utils = require("lib.utils") ---@class Utils

--- Writes colors.rasi to ~/.config/rofi/.
--- @param c table Palette color table from theme.colors.*
return function(c)
  local rasi = string.format(
    [[/** rofi/.config/rofi/colors.rasi — generated by hypr/theme.lua **/

* {
    /* Backgrounds */
    bg-core:    %sFF;
    bg-crust:   %sFF;
    bg-mantle:  %sFF;
    bg-shadow:  %sFF;
    bg-surface: %sFF;

    /* Foregrounds */
    fg-core:   %sFF;
    fg-strong: %sFF;
    fg-muted:  %sFF;
    fg-dim:    %sFF;

    /* Accents */
    theme-primary:   %sFF;
    theme-secondary: %sFF;
    theme-accent:    %sFF;

    /* Status */
    error:   %sFF;
    warning: %sFF;
    info:    %sFF;
    hint:    %sFF;
    ok:      %sFF;

    /* ANSI semantic colors */
    black:          %sFF;
    red:            %sFF;
    green:          %sFF;
    yellow:         %sFF;
    blue:           %sFF;
    magenta:        %sFF;
    cyan:           %sFF;
    white:          %sFF;
    bright-black:   %sFF;
    bright-red:     %sFF;
    bright-green:   %sFF;
    bright-yellow:  %sFF;
    bright-blue:    %sFF;
    bright-magenta: %sFF;
    bright-cyan:    %sFF;
    bright-white:   %sFF;
}
]],
    c.bg_core,
    c.bg_crust,
    c.bg_mantle,
    c.bg_shadow,
    c.bg_surface,
    c.fg_core,
    c.fg_strong,
    c.fg_muted,
    c.fg_dim,
    c.theme_primary,
    c.theme_secondary,
    c.theme_accent,
    c.error,
    c.warning,
    c.info,
    c.hint,
    c.ok,
    c.black,
    c.red,
    c.green,
    c.yellow,
    c.blue,
    c.magenta,
    c.cyan,
    c.white,
    c.bright_black,
    c.bright_red,
    c.bright_green,
    c.bright_yellow,
    c.bright_blue,
    c.bright_magenta,
    c.bright_cyan,
    c.bright_white
  )

  Utils.write_file(HOME .. "/.config/rofi/colors.rasi", rasi)
end
