-- home/hypr/.config/hypr/theme/generate/rofi.lua

local HOME = os.getenv("HOME")
local Utils = require("lib.utils") ---@class Utils

--- Writes colors.rasi to ~/.config/rofi/.
--- @param c table Palette color table from theme.colors.*
return function(c)
  local rasi = string.format(
    [[/** rofi/.config/rofi/colors.rasi — generated by hypr/theme.lua **/

* {
    background:     %sFF;
    background-alt: %sFF;
    foreground:     %sFF;
    selected:       %sFF;
    active:         %sFF;
    urgent:         %sFF;
}
]],
    c.bg_core,
    c.bg_surface,
    c.fg_core,
    c.theme_primary,
    c.yellow,
    c.error
  )

  Utils.write_file(HOME .. "/.config/rofi/colors.rasi", rasi)
end
