-- home/hypr/.config/hypr/theme/generate/swaync.lua

local HOME = os.getenv("HOME")
local Utils = require("lib.utils") ---@class Utils

--- Writes theme-colors.css to ~/.config/swaync/.
--- @param c table Palette color table from theme.colors.*
return function(c)
  local css = string.format(
    [[/* swaync/.config/swaync/theme-colors.css — generated by hypr/theme.lua */

:root {
  /* Backgrounds */
  --bg-core:    %s;
  --bg-mantle:  %s;
  --bg-shadow:  %s;
  --bg-surface: %s;

  /* Foregrounds */
  --fg-core:   %s;
  --fg-strong: %s;
  --fg-muted:  %s;
  --fg-dim:    %s;

  /* Accents */
  --primary:   %s;
  --secondary: %s;
  --accent:    %s;

  /* Status */
  --error:   %s;
  --warning: %s;
  --ok:      %s;

  /* ANSI */
  --red:     %s;
  --green:   %s;
  --blue:    %s;
  --yellow:  %s;
  --cyan:    %s;
  --magenta: %s;
}
]],
    c.bg_core,
    c.bg_mantle,
    c.bg_shadow,
    c.bg_surface,
    c.fg_core,
    c.fg_strong,
    c.fg_muted,
    c.fg_dim,
    c.theme_primary,
    c.theme_secondary,
    c.theme_accent,
    c.error,
    c.warning,
    c.ok,
    c.red,
    c.green,
    c.blue,
    c.yellow,
    c.cyan,
    c.magenta
  )

  Utils.write_file(HOME .. "/.config/swaync/theme-colors.css", css)
end
