-- home/hypr/.config/hypr/theme/generate/waybar.lua

local HOME = os.getenv("HOME")
local utils = require("lib.utils") ---@class utils

--- Writes theme-colors.css to ~/.config/waybar/.
--- @param c table Palette color table from theme.colors.*
return function(c)
  local css = string.format(
    [[/* waybar/.config/waybar/theme-colors.css — generated by hypr/theme.lua */

/* Backgrounds */
@define-color bg_core    %s;
@define-color bg_mantle  %s;
@define-color bg_shadow  %s;
@define-color bg_surface %s;

/* Foregrounds */
@define-color fg_core   %s;
@define-color fg_strong %s;
@define-color fg_muted  %s;
@define-color fg_dim    %s;

/* Accents */
@define-color primary   %s;
@define-color secondary %s;
@define-color accent    %s;
@define-color yellow    %s;

/* Status */
@define-color error   %s;
@define-color warning %s;
@define-color info    %s;
@define-color hint    %s;
@define-color ok      %s;

/* ANSI */
@define-color red     %s;
@define-color green   %s;
@define-color blue    %s;
@define-color cyan    %s;
@define-color magenta %s;
]],
    c.bg_core,
    c.bg_mantle,
    c.bg_shadow,
    c.bg_surface,
    c.fg_core,
    c.fg_strong,
    c.fg_muted,
    c.fg_dim,
    c.theme_primary,
    c.theme_secondary,
    c.theme_accent,
    c.yellow,
    c.error,
    c.warning,
    c.info,
    c.hint,
    c.ok,
    c.red,
    c.green,
    c.blue,
    c.cyan,
    c.magenta
  )

  utils.write_file(HOME .. "/.config/waybar/theme-colors.css", css)
end
