-- home/hypr/.config/hypr/theme/init.lua

local HOME = os.getenv("HOME")
local Config = require("config")
local utils = require("lib.utils")

local Theme = {}

--- Loads the theme file for Config.theme and caches colors on Theme.colors.
--- @return table
Theme.load = function()
  Theme.colors = require("theme.colors." .. Config.theme)
  return Theme.colors
end

--- Applies cached theme colors to Hyprland borders and shadow via hl.config().
Theme.update_hyprland = function(c)
  hl.config({
    general = {
      col = {
        active_border = c.theme_primary,
        inactive_border = c.bg_mantle,
      },
    },
    decoration = {
      shadow = { color = c.bg_shadow },
    },
  })
end

--- Writes theme-colors.css to ~/.config/waybar/ and restarts waybar + swaync.
Theme.update_waybar = function(c)
  local css = string.format(
    [[/* waybar/.config/waybar/theme-colors.css — generated by hypr/theme.lua */

/* Backgrounds */
@define-color bg_core    %s;
@define-color bg_mantle  %s;
@define-color bg_shadow  %s;
@define-color bg_surface %s;

/* Foregrounds */
@define-color fg_core   %s;
@define-color fg_strong %s;
@define-color fg_muted  %s;
@define-color fg_dim    %s;

/* Accents */
@define-color primary   %s;
@define-color secondary %s;
@define-color accent    %s;
@define-color yellow    %s;

/* Status */
@define-color error   %s;
@define-color warning %s;
@define-color info    %s;
@define-color hint    %s;
@define-color ok      %s;

/* ANSI */
@define-color red     %s;
@define-color green   %s;
@define-color blue    %s;
@define-color cyan    %s;
@define-color magenta %s;
]],
    c.bg_core,
    c.bg_mantle,
    c.bg_shadow,
    c.bg_surface,
    c.fg_core,
    c.fg_strong,
    c.fg_muted,
    c.fg_dim,
    c.theme_primary,
    c.theme_secondary,
    c.theme_accent,
    c.yellow,
    c.error,
    c.warning,
    c.info,
    c.hint,
    c.ok,
    c.red,
    c.green,
    c.blue,
    c.cyan,
    c.magenta
  )

  utils.write_file(HOME .. "/.config/waybar/theme-colors.css", css)
  hl.dsp.exec_cmd(
    "pkill waybar; waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css > /dev/null 2>&1 &"
  )
  hl.dsp.exec_cmd("pkill swaync; swaync &")
end

--- Writes theme-colors.rasi to ~/.config/rofi/.
Theme.update_rofi = function(c)
  local rasi = string.format(
    [[/** rofi/.config/rofi/colors.rasi — generated by hypr/theme.lua **/

* {
    background:     %sFF;
    background-alt: %sFF;
    foreground:     %sFF;
    selected:       %sFF;
    active:         %sFF;
    urgent:         %sFF;
}
]],
    c.bg_core,
    c.bg_surface,
    c.fg_core,
    c.theme_primary,
    c.yellow,
    c.error
  )

  utils.write_file(HOME .. "/.config/rofi/colors.rasi", rasi)
end

--- Writes theme.conf to ~/.config/hypr/ with all color variables for sourcing in hyprlock etc.
Theme.update_conf = function(c)
  local function rgb(hex) return "rgb(" .. hex:gsub("^#", "") .. ")" end
  local function rgba(hex, a) return "rgba(" .. hex:gsub("^#", "") .. a .. ")" end

  local lines = {}
  for key, hex in pairs(c) do
    table.insert(lines, string.format("$%s = %s", key, rgb(hex)))
    table.insert(lines, string.format("$%s_faded = %s", key, rgba(hex, "99")))
  end
  table.sort(lines)

  utils.write_file(HOME .. "/.config/hypr/theme.conf", table.concat(lines, "\n") .. "\n")
end

--- Applies all theme generators and reloads affected services.
Theme.apply = function()
  local c = Theme.colors or Theme.load()
  Theme.update_hyprland(c)
  Theme.update_waybar(c)
  Theme.update_rofi(c)
  Theme.update_conf(c)
end

Theme.load()
Theme.apply()

return Theme
