.pragma library

// One tok(name, export type, default, doc, options) per token; the default is a value or (t, c) => value, null leaves it out.
// Options: expr (the export's binding), via: "bar", export: false (internal). Run scripts/gen-style-exports after editing.
function tok(name, type, value, doc, opts) {
    return Object.assign({ name: name, type: type, value: value, doc: doc }, opts);
}

var tokens = [
    tok("pal", "var", (t, c) => c.pal, ""),
    tok("wk", "var", (t, c) => c.theme_tokens.wk, "The watch's colour ramp and panel gradient for the current mode: tinted from the palette, or the classic green when goldeneye's Watch colours is Classic."),
    tok("watch_mode", "string", null, "The saved Watch colours choice, whatever the current style is (the lock skin reads it).", {expr: '(root.theme_values.goldeneye || {}).watch_colors || "Theme"'}),
    tok("text_muted", "color", t => t.fg_muted, ""),
    tok("text_dim", "color", t => t.fg_dim, ""),
    tok("text_fg", "color", t => t.fg_core, ""),
    tok("text_strong", "color", t => t.fg_strong, ""),
    tok("text_primary", "color", t => t.theme_primary, "Primary and secondary colored text in popups."),
    tok("text_accent", "color", t => t.theme_secondary, ""),
    tok("font_family", "string", "JetBrainsMono Nerd Font", ""),
    tok("font_size", "int", t => t.popup_font_size + 2, ""),
    tok("number_font", "string", "", "Big readouts (weather temperature, OSD percentage); empty uses font_family.", {expr: 'root.active.number_font !== "" ? root.active.number_font : root.font_family'}),
    tok("title_font_family", "string", "", "", {expr: "root.active.title_font_family || root.font_family"}),
    tok("rounded", "bool", false, ""),
    tok("frame_follows_island", "bool", false, ""),
    tok("frame_color", "color", t => t.bg_crust, ""),
    tok("frame_radius", "real", 0, ""),
    tok("frame_border_width", "int", 1, ""),
    tok("frame_border_color", "color", t => t.fg_muted, ""),
    tok("frame_chamfer", "real", 0, "Bottom corners cut at 45 degrees by this many px."),
    tok("frame_visor", "bool", false, "Frames drawn as visor glass (VisorGlass) instead of a plain rectangle."),
    tok("frame_inset_gap", "int", 0, "An inner ring frame_inset_gap inside the border; content keeps inset_pad clear of the frame edge."),
    tok("frame_inset_width", "int", 0, ""),
    tok("frame_inset_color", "color", "transparent", ""),
    tok("inset_pad", "int", null, "", {expr: "root.frame_inset_width > 0 ? root.frame_border_width + root.frame_inset_gap + root.frame_inset_width : root.active.frame_pad"}),
    tok("frame_pad", "int", 0, "Content padding inside a frame with no inset ring (read by inset_pad).", {export: false}),
    tok("frame_drop", "int", 0, "A hard shadow this many px below floating frames."),
    tok("lcd_top", "color", "transparent", "A panel lcd_margin inside the frame, shaded lcd_top to lcd_bottom, that holds the title, body and footer."),
    tok("lcd_bottom", "color", "transparent", ""),
    tok("lcd_scan", "color", "transparent", ""),
    tok("lcd_margin", "int", 0, ""),
    tok("frame_engraving", "string", "", "Lettering on the frame under the panel."),
    tok("frame_watch", "bool", false, "Draws the popup panel as the watch's green octagon."),
    tok("link_style", "string", "", '"watch" words the network and bluetooth popups in the mission language, with dial headers and segment bars.'),
    tok("overview_skin", "string", "", 'Overview treatment: "" keeps the shared look, "goldeneye" adds the `N | M` window counter, a monochrome tint on unselected windows and the lock-on crosshair, "scope" the MGS aiming reticle.'),
    tok("toast_mission", "bool", false, "Toasts carry the mission wording (INCOMING, MISSION CRITICAL) in their header."),
    tok("track_bars", "bool", false, "Track progress as the lock face's row of green bars."),
    tok("open_fx", "string", "", "\"static\" plays the watch's static over a popup as it opens."),
    tok("confirm_layout", "string", "", "\"watch\" asks for a Power action in the lock skin's arm-then-confirm words."),
    tok("accent_color", "color", t => t.theme_secondary, ""),
    tok("accent_height", "int", 3, ""),
    tok("accent_full_width", "bool", true, ""),
    tok("frame_top_rule", "bool", false, "Frames without a popup accent line (OSD, toasts) draw one along their top edge."),
    tok("selection_bg", "color", "transparent", ""),
    tok("selection_inverse", "bool", false, ""),
    tok("selection_fg", "color", t => t.bg_crust, ""),
    tok("caret_color", "color", t => t.theme_secondary, ""),
    tok("caret_blink", "bool", true, ""),
    tok("selection_outline", "color", t => Qt.alpha(t.theme_secondary, 0.6), ""),
    tok("tab_active_bg", "color", t => t.theme_secondary, ""),
    tok("tab_active_fg", "color", t => t.bg_crust, ""),
    tok("tab_fg", "color", t => t.fg_muted, ""),
    tok("tab_caps", "bool", false, ""),
    tok("tab_underline", "color", "transparent", ""),
    tok("key_bg", "color", "transparent", ""),
    tok("key_fg", "color", t => t.fg_muted, ""),
    tok("key_border", "color", t => t.bg_surface, ""),
    tok("section_fg", "color", t => t.fg_muted, ""),
    tok("section_rule", "bool", true, ""),
    tok("label_caps", "bool", false, "Section headers and footer descriptions in tracked caps."),
    tok("label_spacing", "real", 0, ""),
    tok("section_fade", "color", "transparent", "A rule after section labels that fades out to the right."),
    tok("footer_fg", "color", t => t.fg_muted, ""),
    tok("footer_key_fg", "color", t => t.theme_secondary, ""),
    tok("footer_rule", "bool", true, ""),
    tok("footer_rule_color", "color", t => t.bg_surface, ""),
    tok("meter_on", "color", t => t.theme_primary, ""),
    tok("meter_off", "color", t => t.bg_surface, ""),
    tok("meter_hot", "color", t => t.theme_label, ""),
    tok("meter_radius", "real", 0, ""),
    tok("meter_outline", "color", "transparent", "Outlines every meter segment; lit hot segments take meter_hot instead."),
    tok("scale", "real", 1.15, ""),
    tok("popup_min_width", "real", 0, "Floor for every popup's width, for wide fonts that overrun the small popups."),
    tok("show_title", "bool", true, ""),
    tok("title_bg", "color", t => t.theme_secondary, ""),
    tok("title_fg", "color", t => t.bg_crust, ""),
    tok("show_footer", "bool", true, ""),
    tok("footer_wrap", "bool", true, ""),
    tok("row_cursor", "string", ">", ""),
    tok("segmented_levels", "bool", true, "Closes the cursor at the selected row's right end, before its key badge."),
    tok("tab_keys", "bool", true, ""),
    tok("row_keys", "bool", true, ""),
    tok("boxed_cards", "bool", true, ""),
    tok("chip_brackets", "bool", true, ""),
    tok("chip_active_bg", "color", "transparent", ""),
    tok("chip_active_fg", "color", t => t.theme_primary, ""),
    tok("chip_pick", "color", t => t.theme_secondary, "A picked action chip's fill; chip_border outlines the rest, key_border when transparent."),
    tok("chip_border", "color", "transparent", ""),
    tok("card_edge", "color", "transparent", ""),
    tok("toggle_brackets", "bool", true, ""),
    tok("toggle_on", "color", t => t.ok, ""),
    tok("toggle_off", "color", t => t.fg_muted, ""),
    tok("marker_fill", "bool", true, ""),
    tok("selection_bar", "bool", false, ""),
    tok("title_prefix", "string", "", ""),
    tok("title_suffix", "string", "", ""),
    tok("title_spacing", "real", 2, ""),
    tok("title_readout", "string", "", "A static system readout drawn at the right end of the title row."),
    tok("title_readout_fg", "color", "transparent", "Transparent draws the readout in text_muted; {code} in the readout becomes the title's first three letters."),
    tok("title_rule", "color", "transparent", ""),
    tok("frame_glow", "color", "transparent", ""),
    tok("scanlines", "bool", false, ""),
    tok("scanline_color", "color", "transparent", ""),
    tok("scanline_period", "int", 3, "Rows per scanline; 2 cuts every row of a 2x pixel font alike."),
    tok("glow", "bool", false, ""),
    tok("glow_color", "color", "transparent", ""),
    tok("glow_tint", "real", 0, ""),
    tok("frame_shade", "color", "transparent", "A diagonal shade from this color at the top left into frame_color."),
    tok("shade_vertical", "bool", false, "Runs frame_shade top to bottom instead of diagonally."),
    tok("dither", "color", "transparent", ""),
    tok("text_shadow", "color", "transparent", ""),
    tok("fade_fills", "bool", false, "Selection and title fills fade out to the right."),
    tok("selection_border", "color", "transparent", ""),
    tok("selection_glow", "color", "transparent", ""),
    tok("meter_shade", "color", "transparent", ""),
    tok("meter_slant", "real", 0, "Leans meter and waveform tops right by this shear per px of height."),
    tok("meter_bloom", "bool", false, "A blurred copy of the whole meter behind it."),
    tok("chart_slant", "real", 0, "Leans chart bars like meter_slant."),
    tok("chart_fill", "color", t => t.yellow, ""),
    tok("corner_scale", "real", 1, "Multiplies every radius a rounded style draws."),
    tok("mono_font", "string", "", "Readouts, keys and ids; empty uses font_family.", {expr: "root.active.mono_font || root.font_family"}),
    tok("selection_rule", "color", "transparent", "A 1px rule under the selected row."),
    tok("tab_bg", "color", "transparent", ""),
    tok("chip_bg", "color", "transparent", ""),
    tok("meter_height", "real", 0, "0 keeps the default height."),
    tok("footer_key_bg", "color", "transparent", "Footer keys drawn as filled caps in footer_key_fg on this color."),
    tok("footer_separator", "string", " \u00b7 ", ""),
    tok("footer_rule_solid", "bool", false, ""),
    tok("osd_layout", "string", "", 'Alternate layouts (OSD ones are Style.osd_layouts, weather ones Style.weather_layouts): "" keeps the default; osd "ring", "hud", "rpg", "alert", "glow", "horizon" or "tile", weather "ring", "scope", "watch", "memcard", "battle", "mode7", "wttr", "weatherstar", "towers", "scan", "hev", "pokedex", "status", "oasis", "hero" or "lsp", cards "rule", "pixel", "dq", "dialogue", "dialog", "oasis", "tile" or "notify".'),
    tok("level_layout", "string", "", 'Level rows: "capsule" draws them as tall capsule sliders with live peaks, "slant" and "visor" the same with slanted ends or visor glass (Volume popup and OSD only); "" keeps the shared slider.'),
    tok("card_layout", "string", "", ""),
    tok("weather_header", "string", "", ""),
    tok("picker_skin", "string", "", 'Picker and region cursor/loupe/target treatment, one of Style.picker_skins: "" keeps the shared look, "scope" swaps in the MGS binocular skin.'),
    tok("picker_hud", "color", t => t.theme_secondary, ""),
    tok("picker_hint_keys", "string", "", "Keys that pick a target by position, live only under the skins that draw them (a borrowed keyless skin would leave them as invisible shortcuts); those fall back to the digits 1-9.", {expr: '["nvimfloat", "tmux", "tvosd"].indexOf(root.active.picker_skin) >= 0 ? (root.active.picker_hint_keys || "123456789") : ""'}),
    tok("bar_pill_square", "bool", false, "Square-cornered workspace pills; bar_workspace_diamond also turns the empty ones into diamonds.", {via: "bar"}),
    tok("bar_font_family", "string", "JetBrainsMono Nerd Font", "", {via: "bar"}),
    tok("bar_font_size", "int", t => t.font_size, "", {via: "bar"}),
    tok("bar_capitalization", "int", null, "Text labels only; glyphs are unaffected.", {expr: "root.bar.bar_caps ? Font.AllUppercase : Font.MixedCase"}),
    tok("bar_caps", "bool", false, "Bar text labels in caps (read by bar_capitalization).", {export: false}),
    tok("bar_letter_spacing", "real", 0, "", {via: "bar"}),
    tok("bar_side_bg", "color", t => t.bg_crust, "", {via: "bar"}),
    tok("bar_center_bg", "color", t => t.bg_crust, "", {via: "bar"}),
    tok("bar_fg", "color", t => t.fg_core, "", {via: "bar"}),
    tok("bar_clock_bg", "color", "transparent", "The clock's time sits on a chip of this color when it is not transparent.", {via: "bar"}),
    tok("bar_clock_fg", "color", t => t.fg_core, "", {via: "bar"}),
    tok("bar_clock_font", "string", "", "", {expr: "root.bar.bar_clock_font || root.bar_font_family"}),
    tok("bar_clock_size", "int", 0, "Clock icon and time size in px; 0 keeps the style's own size.", {via: "bar"}),
    tok("bar_glyph_size", "int", 0, "Bar module glyphs; 0 in a style keeps Theme.glyph_size.", {expr: "root.bar.bar_glyph_size > 0 ? root.bar.bar_glyph_size : Theme.glyph_size"}),
    tok("bar_badge_size", "int", null, "", {expr: "root.bar.bar_glyph_size > 0 ? Math.round(root.bar.bar_glyph_size * 0.62) : Math.max(6, root.bar_font_size - 3)"}),
    tok("bar_border_width", "int", 1, "", {via: "bar"}),
    tok("bar_border_color", "color", t => t.fg_muted, "", {via: "bar"}),
    tok("bar_rounded", "bool", false, "", {via: "bar"}),
    tok("bar_workspace_focused", "color", t => t.theme_secondary, "Focused is the workspace you are on; active is the one shown on each other monitor.", {via: "bar"}),
    tok("bar_workspace_active", "color", t => t.theme_primary, "", {via: "bar"}),
    tok("bar_workspace_idle", "color", t => t.bg_surface, "", {via: "bar"}),
    tok("bar_workspace_ring", "color", "transparent", "", {via: "bar"}),
    tok("bar_inset_gap", "int", 0, "An inner line along each island's slants and bottom edge.", {via: "bar"}),
    tok("bar_inset_width", "int", 0, "", {via: "bar"}),
    tok("bar_inset_color", "color", "transparent", "", {via: "bar"}),
    tok("bar_hover_bg", "color", t => t.bg_surface, "", {via: "bar"}),
    tok("bar_glow_color", "color", "transparent", "", {via: "bar"}),
    tok("bar_text_raised", "bool", false, "Raised bar text (read by bar_text_style).", {export: false}),
    tok("done_anim", "string", "hearts", "The keeptabs done celebration (Style.done_anims): hearts, pixel (stepped), lcd (stepped, then blinks), hev_pickup, levelup (inverted flash, pixel sparkles) or fanfare.", {expr: 'root.active.done_anim || "hearts"'}),
    tok("wait_anim", "string", "bubble", "The keeptabs waiting cue (Style.wait_anims): bubble, cursor, pressanykey, advance, hand, alert, rumble, transmission, scan, comms, ping, hev_alert, exclaim or atb.", {expr: 'root.active.wait_anim || "bubble"'}),
    tok("bar_scanline_color", "color", "transparent", "", {via: "bar"}),
    tok("label_font_family", "string", "", "Sections, tabs and chips; empty uses font_family.", {expr: "root.active.label_font_family || root.font_family"}),
    tok("frame_octagon", "real", 0, "Frames cut to an octagon this many px at each corner (OctagonFrame)."),
    tok("frame_struts", "color", "transparent", "Diagonal struts from the octagon's cut corners and ticks at its edge midpoints."),
    tok("custom_frame", "bool", null, "A frame component draws the fill and border, so the base rectangle and FrameShade stay empty.", {expr: "root.frame_octagon > 0 || root.slant_frame"}),
    tok("lcd_radius", "real", 8, ""),
    tok("lcd_border", "color", t => Qt.alpha(t.bg_shadow, 0.6), ""),
    tok("lcd_brackets", "color", "transparent", "Corner brackets at all four corners inside the LCD panel."),
    tok("selection_brackets", "color", "transparent", "Target-lock corner brackets on selected rows, cards and days."),
    tok("tab_brackets", "color", "transparent", "Brackets around the active tab's label."),
    tok("tab_rule", "color", "transparent", "A 1px baseline under every tab."),
    tok("title_reticle", "color", "transparent", "A reticle glyph before popup titles."),
    tok("chart_outline", "color", "transparent", ""),
    tok("bar_workspace_diamond", "bool", false, "", {via: "bar"}),
    tok("bar_clock_brackets", "color", "transparent", "Brackets around the bar clock's time.", {via: "bar"}),
    tok("bar_separator", "string", "", '"tick" draws the white watch bar between bar items in place of "|".', {via: "bar"}),
    tok("bar_tick_color", "color", null, "The watch tick and separator colour: white on a dark center island, the foreground on a light one.", {expr: "root.bar.bar_center_bg.hslLightness > 0.6 ? Theme.fg_core : Watch.white"}),
    tok("bar_island_shape", "string", "", '"octagon" draws chamfered watch-case bar islands (the center one with lugs) with a white tick at each end.', {via: "bar"}),
    tok("hairline", "color", "transparent", "Major and minor tick color for frame scales, rules and ruler meters."),
    tok("hairline_dim", "color", "transparent", ""),
    tok("frame_ticks", "string", "", '"top": a tick scale on the top edge, bottom rule and corner crosses; "left": a scale down the left side and a corner ring.'),
    tok("tick_ruler", "bool", false, ""),
    tok("range_line", "bool", false, "Daily temperature ranges as 1px lines with ring end caps."),
    tok("key_round", "bool", false, ""),
    tok("pill_chips", "bool", false, "Chips, action chips, header buttons and the alert banner as outlined pills."),
    tok("title_index", "var", () => [], "Popup names numbered 01, 02, ... in front of their titles."),
    tok("title_weight", "int", 0, "0 keeps titles bold when they share the body font."),
    tok("title_trail", "color", "transparent", "A rule from the title to the readout, fading out to the right."),
    tok("bar_ticks", "color", "transparent", "A tick scale rising from each island's bottom edge.", {via: "bar"}),
    tok("title_strip", "color", "transparent", "A full-width title strip in this color with a hairline under it and a close box at the right."),
    tok("caps_tracking", "real", 0, "Sections, tabs, chips and header buttons in caps tracked this far; footers keep label_caps."),
    tok("tab_outline", "color", "transparent", "A 1px outline around every tab and header button; the active tab takes selection_border."),
    tok("shade_0", "color", "transparent", "A four-shade screen palette, darkest first, for pixel-art parts (sprites, photos, dot bars)."),
    tok("shade_1", "color", "transparent", ""),
    tok("shade_2", "color", "transparent", ""),
    tok("shade_3", "color", "transparent", ""),
    tok("pixel_border", "color", "transparent", "Frames get a 2px pixel double border with this middle ring (PixelFrame); keys and meters get 2px pixel rings."),
    tok("device_shell", "bool", false, "Small popups sit inside a handheld's shell (DeviceShell); hover shelves never do."),
    tok("device_model", "string", "", "Which handheld the shell draws: dmg or color."),
    tok("window_gradient", "var", () => [], "Diagonal [position, color] stops filling window frames inside their border (WindowGradient); empty keeps frame_color."),
    tok("materia", "var", () => ({}), "Orb colors (MateriaOrb) by role (key, section, workspace, alert), weather kind and daily slot color; a role left out draws no orb."),
    tok("hand_cursor", "bool", false, "A pointing hand (HandCursor) on the selected row, active tab, picked chip and selected day."),
    tok("meter_solid", "bool", false, "Meters as one continuous gauge (AtbBar) instead of segments."),
    tok("controller", "string", "", "Key badges, footers and help draw this console's buttons (KeyHints.controllers); Controller glyphs Off blanks it, so read it for glyphs only."),
    tok("controller_glyphs", "string", "dpad", 'Which keys draw as controller buttons: "all", "labeled" (the key beside each button the d-pad and shoulders cannot explain), "dpad" (only those) or "off".'),
    tok("meter_art", "var", () => ({}), 'Meter art by popup name (or "osd"): a component path relative to components/ that replaces the segments.'),
    tok("toast_enter", "string", "", 'Toast arrival: "" fades in; "type" slides and types, "mode7" zooms from a tilted plane, "wobble" settles, "bloom" glows, each once.'),
    tok("console_views", "string", "", "Popups, toasts and bar modules swap in this console's views (\"nes\", \"snes\", \"ps1\", \"ps2\"); \"\" keeps the shared ones."),
    tok("workspace_art", "string", "", 'Bar workspace indicator art ("dial", "materia", "doors", "constellation", "buffers", "party"), one of Style.workspace_arts; "" keeps pills.'),
    tok("slant_frame", "bool", false, "Frames drawn by SlantFrame: flat top, bottom corners cut at the bar islands' slant, a sand horizon along the foot."),
    tok("slant_room", "int", null, "Extra room under a frame's content so the long cut clears the footer.", {expr: "root.slant_frame ? 8 : 0"}),
    tok("footer_moon", "bool", false, "A small sand crescent at the right end of the footer rule."),
    tok("footer_compass", "bool", false, "A visor heading tape in place of the dashed footer rule."),
    tok("selection_edge", "color", "transparent", "A lit edge down the left of the selected row."),
    tok("chip_tabs", "bool", false, "Sub-view chips drawn as tabs that fill their row."),
    tok("title_case", "bool", false, 'Popup, OSD and which-key titles in title case ("NETWORK" to "Network", see title_text); title_size 0 keeps font_size - 2.'),
    tok("title_size", "int", 0, ""),
    tok("frame_float", "int", 0, "Popups float this many px below the bar with every corner rounded; frame_shadow fills frame_drop's room with a soft shadow."),
    tok("frame_shadow", "color", "transparent", ""),
    tok("sheen", "color", "transparent", "A 1px highlight (Sheen) along the top of raised surfaces: floating frames, capsule islands, shaded tabs and rows, keycaps, cards."),
    tok("selection_shade", "color", "transparent", ""),
    tok("tab_well", "color", "transparent", "Tab and chip rows sit in a recessed well of this color; tab_marker then draws as a dash under the active label."),
    tok("tab_active_shade", "color", "transparent", "Top colors of vertical gradients into tab_active_bg (raised active tabs and chips) and selection_bg (selected rows)."),
    tok("tab_key_plain", "bool", false, "Tab jump keys as bare digits instead of badges."),
    tok("title_status", "bool", false, "The popup's live title value at the right of its title (in the border under border_title)."),
    tok("chip_fg", "color", "transparent", "Action chip text; transparent keeps theme_secondary."),
    tok("bar_capsule", "int", 0, "Islands as floating capsules this many px inside the bar's top and ends, resting on its bottom edge; 0 keeps the slanted islands.", {via: "bar"}),
    tok("bar_capsule_pad", "int", 0, "", {via: "bar"}),
    tok("bar_height", "int", 0, "Bar height when bars.json sets none; 0 keeps the default.", {via: "bar"}),
    tok("bar_module_gap", "int", 16, "", {via: "bar"}),
    tok("bar_pill_height", "int", 0, "Plain workspace pills: height (0 keeps the default), extra room each side of their icons, and the gap between them.", {via: "bar"}),
    tok("bar_pill_pad", "int", 0, "", {via: "bar"}),
    tok("bar_workspace_gap", "int", 0, "", {via: "bar"}),
    tok("bar_workspace_shade", "color", "transparent", "", {via: "bar"}),
    tok("bar_workspace_dot", "color", "transparent", "Empty workspaces as small dots of this color instead of pills.", {via: "bar"}),
    tok("bar_clock_layout", "string", "", 'Bar clock layout: "capsule" (time with a small zone, a hairline and the date) or "horizon" (a horizon with the sun or moon in the center island).', {via: "bar"}),
    tok("bar_start_well", "color", "transparent", "", {via: "bar"}),
    tok("border_title", "bool", false, "Frames drawn as Neovim floating windows (FloatFrame): rounded all round, the title as a chip set into the top border."),
    tok("row_gutter", "bool", false, "Rows get a line-number gutter showing their key; the selected row's number takes text_accent."),
    tok("tab_marker", "color", "transparent", "The active tab's marker: a 2px bar down its left edge, or a dash under its label in a tab_well."),
    tok("section_fold", "bool", false, "Sections as open folds: a fold marker, the label and a dotted fill."),
    tok("footer_arrow", "string", "", "Drawn between each footer key and its description."),
    tok("footer_italic", "bool", false, ""),
    tok("footer_size", "int", 0, "Footer text size in px; 0 keeps the popup-derived sizes."),
    tok("key_size", "int", 0, "Key cap and tab jump key text size in px; 0 keeps fs(-5)."),
    tok("whichkey_arrow", "string", "", ""),
    tok("whichkey_size", "int", 0, "Which-key keys and labels in px; 0 keeps the popup-derived sizes."),
    tok("type_scale", "var", () => ({}), "Maps a text role's offset from font_size to the style's own (e.g. {\"-2\": 0} lifts -2 text to full size); unlisted offsets pass through.", {expr: "root.active.type_scale || ({})"}),
    tok("meter_gap", "real", 2, ""),
    tok("meter_palette", "string", "", '"bezel" colours a level meter warm for its first half and blue for the second, dim when unlit.'),
    tok("bar_lualine", "bool", false, "A lualine statusline: flat sections with arrow separators, the start button as the HyprVim mode chip.", {via: "bar"}),
    tok("bar_text_style", "int", null, "", {expr: "root.bar.bar_text_raised ? Text.Raised : root.bar_glow_color.a > 0 ? Text.Outline : Text.Normal"}),
    tok("small", "var", null, "Overrides for popups whose size_class is small.", {export: false}),
    tok("models", "var", null, "Full token sets by device model, picked with the device_model option.", {export: false}),
    tok("model_labels", "var", null, "Labels for the device_model option by model.", {export: false}),
    tok("watch_classic", "var", null, "Tokens laid over the style when the watch_colors option is Classic.", {export: false}),
    tok("watch_colors", "string", null, "The watch colour choice, Theme or Classic.", {export: false})
];

// The base token set every style starts from; t is Theme, c holds the palette slots and watch tokens.
function defaults(t, c) {
    const o = {};
    for (const k of tokens) {
        if (k.value !== null) o[k.name] = typeof k.value === "function" ? k.value(t, c) : k.value;
    }
    return o;
}
