# starship/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](bright_black)[](yellow)$os$username$sudo[](fg:yellow)\
$hostname$localip\
[](fg:bright_yellow)$directory[](fg:bright_yellow)\
$git_branch$git_status\
$cmd_duration\
$status\
$fill\
$c$rust$golang$nodejs$lua$php$java$kotlin$haskell$python\
$docker_context$conda\
[](fg:gray bg:none)$time[](fg:gray bg:none)\
[ ](fg: none bg: none)$line_break\
[╰─](fg:bright_black)$character\
"""

#Shapes
# [](fg:bright_yellow)
# [](fg:bright_yellow)
# [─](fg:bright_black)
# [](fg:green)
# [](fg:green)\

palette = 'oasis'
[palettes.oasis]
white = '#FFF7D7'
black = '#101825'
gray = '#514742'
bright_black = '#877363'
bright_blue = '#87CEEB'
cyan = '#8FD1C7'
green = '#8FED88'
yellow = '#F0E68C'
bright_yellow = '#F8B471'
magenta = '#C695FF'
red = '#FF7979'
bright_red = '#FFA0A0'

[os]
disabled = false
style = "bg:yellow fg:black"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:yellow fg:black"
style_root = "bg:yellow fg:black"
format = '[ $user ]($style)'

[sudo]
style = "bg:yellow fg:black"
disabled = true

[hostname]
ssh_only = true
style = "fg:white bold bg:black"
ssh_symbol = '🌐'
#trim_at = '.companyname.com'
disabled = false
format = '[](fg:red bg:none)[ $ssh_symbol $hostname]($style)'

[localip]
ssh_only = true
style = "fg:black bold bg:red"
format = '[ $localipv4 ](fg:black bg:red)[](fg:red bg:none)'
disabled = false

[directory]
style = "fg:black bg:bright_yellow"
format = "[ $path ]($style)"
home_symbol = ' ~'
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = true
repo_root_format = '[  ](fg:black bg:bright_yellow)[$read_only]($read_only_style)[$before_root_path]($style)[$repo_root]($style)[$path ]($style)'
repo_root_style = 'fg:primt bold bg:prim'

[directory.substitutions]
".config" = ". "
"Developer" = "󰲋 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Videos" = "󰨜 "
"Games" = "󰊴 "
"steam" = " "
"Emulators" = "󰺵 "

[git_branch]
symbol = ""
style = "bg:bright_blue"
format = '[](fg:bright_blue bg:none)[[ $symbol $branch(:$remote_branch) ](fg:black bg:bright_blue)]($style)'

[git_status]
style = "bg:bright_blue"
format = '[[($all_status $ahead_behind)](fg:black bg:bright_blue)]($style)[](fg:bright_blue bg:none)'

[nodejs]
symbol = '󰎙 Node'
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[lua]
symbol = '󰢱 Lua'
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[c]
symbol = " C"
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[rust]
symbol = " Rust"
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[golang]
symbol = " Go"
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[php]
symbol = " Php"
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[java]
symbol = ' Java'
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[kotlin]
symbol = " Kotlin"
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[haskell]
symbol = " Haskell"
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[python]
symbol = ' Python'
style = "bg:magenta"
format = '[](fg:magenta)[[ $symbol( $version) ](fg:black bg:magenta)]($style)[](fg:magenta)[─](fg:bright_black)'

[docker_context]
symbol = ""
style = "bg:bright_black"
format = '[](fg:red)[[ $symbol( $context) ](fg:black bg:red)]($style)[](fg:red)[─](fg:bright_black)'

[conda]
style = "bg:bright_black"
format = '[](fg:red)[[ $symbol( $environment) ](fg:black bg:red)]($style)[](fg:red)[─](fg:bright_black)'

[time]
disabled = false
time_format = " %I:%M%P"
style = "bg:gray"
format = '[[  $time ](fg:white bg:gray)]($style)'

[fill]
symbol = " "

[cmd_duration]
style = "fg:bright_red bg:none"
format = '[]($style)[ 󱐋 $duration ]($style inverted)[]($style)'
min_time = 500
disabled = false

[status]
style = "fg:red bg:none"
disabled = false
format = '[─](fg:bright_black bg:none)[](fg:red bg:none)[$symbol ](fg:black bg:red)[]($style)'
symbol = '   Error'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[](bold yellow)'
vimcmd_replace_one_symbol = '[R](bold cyan)'
vimcmd_replace_symbol = '[R](bold cyan)'
vimcmd_visual_symbol = '[V](bold bright_yellow)'
