-- hypr/.config/hypr/lua-theme/lib/generators/hyprland.lua
-- Hyprland theme generator

local Utils = require("lib.utils")
local BaseGenerator = require("lib.generators.base")

local HyprlandGenerator = setmetatable({}, { __index = BaseGenerator })
HyprlandGenerator.__index = HyprlandGenerator

function HyprlandGenerator:new()
	local obj = BaseGenerator:new()
	setmetatable(obj, self)
	return obj
end

function HyprlandGenerator:generate(palette, output_dir, palette_name)
	local content = string.format(
		[[# hypr/.config/hypr/lua-theme/output/hypr-theme.conf
# Generated by lua-theme/main.lua
# DO NOT EDIT MANUALLY - regenerate with: lua ~/.config/hypr/lua-theme/main.lua

# Color Variables
$bg_core = %s
$bg_mantle = %s
$bg_shadow = %s
$bg_surface = %s
$fg_core = %s
$fg_strong = %s
$fg_muted = %s
$theme_primary = %s
$theme_secondary = %s
$theme_accent = %s
$error = %s
$warning = %s
$info = %s
$hint = %s
$ok = %s

# Apply Theme to Hyprland Sections
general {
  gaps_in = 4
  gaps_out = 6
  border_size = 2
  col.active_border = $theme_primary
  col.inactive_border = $bg_mantle
  resize_on_border = true
  allow_tearing = false
  layout = dwindle
}

decoration {
  rounding = 8
  active_opacity = 0.98
  inactive_opacity = 0.5
  dim_inactive = true
  dim_strength = 0.2

  shadow {
    enabled = true
    range = 4
    render_power = 3
    color = $bg_shadow
  }

  blur {
    enabled = true
    size = 3
    passes = 1
    vibrancy = 0.1696
  }
}

animations {
  enabled = true
  bezier = overshot, 0.13, 0.99, 0.29, 1.1
  animation = workspaces, 1, 6, overshot, slide
  animation = windows,1,4,overshot,slide
  animation = layers,1,5,default,default
}

# Layer rules
layerrule = animation slide top, waybar
layerrule = animation popin, rofi
layerrule = animation fade, hyprpaper
layerrule = animation fade, selection
layerrule = animation slide right, notificationsmenu
layerrule = animation slide left, dashboardmenu

# Dwindle layout
dwindle {
  pseudotile = true
  preserve_split = false
  smart_split = false
}

# Master layout
master {
  new_status = master
}

# Misc settings
misc {
  force_default_wallpaper = -1
  disable_hyprland_logo = true
  animate_manual_resizes = true
}
]],
		Utils.hex_to_hypr(palette.bg_core),
		Utils.hex_to_hypr(palette.bg_mantle),
		Utils.hex_to_hypr(palette.bg_shadow),
		Utils.hex_to_hypr(palette.bg_surface),
		Utils.hex_to_hypr(palette.fg_core),
		Utils.hex_to_hypr(palette.fg_strong),
		Utils.hex_to_hypr(palette.fg_muted),
		Utils.hex_to_hypr(palette.theme_primary),
		Utils.hex_to_hypr(palette.theme_secondary),
		Utils.hex_to_hypr(palette.theme_accent),
		Utils.hex_to_hypr(palette.error),
		Utils.hex_to_hypr(palette.warning),
		Utils.hex_to_hypr(palette.info),
		Utils.hex_to_hypr(palette.hint),
		Utils.hex_to_hypr(palette.ok)
	)

	local output_path = output_dir .. "/hypr-theme.conf"
	return self:write_output(output_path, content)
end

return HyprlandGenerator
