.pragma library

function overrides(t, ctx) {
    return {
        wait_anim: "pressanykey",
        weather_header: "weatherstar",
        text_muted: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.35)),
        text_dim: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.6)),
        // VT323 is tall and narrow; 24 matches the old cap height with room to spare across.
        font_family: "VT323",
        font_size: t.popup_font_size + 9,
        frame_border_color: Qt.tint(t.bg_crust, Qt.alpha(t.theme_primary, 0.35)),
        frame_glow: t.ui_visual_bg,
        accent_color: t.theme_primary,
        picker_skin: "tvosd",
        picker_hint_keys: "123456789",
        selection_bg: Qt.alpha(t.theme_primary, 0.14),
        selection_outline: "transparent",
        selection_bar: true,
        row_cursor: "\u25b6",
        tab_active_bg: Qt.alpha(t.theme_primary, 0.2),
        tab_active_fg: t.theme_secondary,
        tab_fg: t.theme_primary_strong,
        key_fg: t.theme_secondary,
        key_border: Qt.alpha(t.theme_secondary, 0.35),
        section_fg: t.theme_primary_strong,
        footer_fg: t.theme_primary_strong,
        footer_rule_color: Qt.alpha(t.theme_primary, 0.3),
        meter_off: Qt.alpha(t.theme_primary, 0.15),
        meter_hot: t.theme_label,
        title_bg: "transparent",
        title_fg: t.theme_secondary,
        title_prefix: "> ",
        title_suffix: "_",
        chip_active_fg: t.theme_secondary,
        scanlines: true,
        scanline_color: Qt.alpha(t.bg_shadow, 0.3),
        glow: true,
        glow_color: t.theme_primary,
        glow_tint: 0.25,
        bar_font_family: "VT323",
        bar_font_size: t.font_size + 5,
        bar_fg: t.theme_primary_light,
        bar_border_color: Qt.alpha(t.theme_primary, 0.5),
        bar_hover_bg: Qt.alpha(t.theme_primary, 0.4),
        bar_glow_color: Qt.alpha(t.theme_primary, 0.3),
        bar_scanline_color: Qt.alpha(t.theme_primary, 0.07)
    };
}
