.pragma library

// A Game Boy screen; `small` popups sit in the handheld's shell. The original is four shades of the primary, the Color shows the palette.
function overrides(t, ctx) {
    const build = (model, shades, colors) => {
        const [g0, g1, g2, g3] = shades;
        return Object.assign({}, ctx.defaults, {
            device_model: model,
            wait_anim: "exclaim",
            done_anim: "levelup",
            weather_header: "pokedex",
            card_layout: "pixel",
            picker_skin: "pokemon",
            shade_0: g0,
            shade_1: g1,
            shade_2: g2,
            shade_3: g3,
            controller: "gameboy",
            workspace_art: "party",
            pixel_border: g2,
            text_muted: g2,
            text_dim: g2,
            text_fg: g3,
            text_strong: g3,
            text_primary: g3,
            text_accent: g3,
            // Silkscreen and Press Start 2P sit on an 8px grid; 16 is Silkscreen's 2x size.
            font_family: "Silkscreen",
            font_size: 16,
            // Keys and footers at Silkscreen's 2x; fs(-5) and fs(-4) fall off its 8px grid and blur.
            key_size: 16,
            footer_size: 16,
            title_font_family: "Press Start 2P",
            number_font: "Press Start 2P",
            mono_font: "Press Start 2P",
            frame_color: g1,
            frame_border_width: 0,
            frame_border_color: g2,
            frame_pad: 6,
            accent_color: g2,
            accent_height: 0,
            selection_bg: g3,
            selection_inverse: true,
            selection_fg: g0,
            selection_outline: "transparent",
            caret_color: g0,
            row_cursor: "\u25b6",
            tab_active_bg: g3,
            tab_active_fg: g0,
            tab_fg: g2,
            key_fg: g3,
            key_border: g2,
            section_fg: g2,
            section_rule: false,
            section_fade: g2,
            footer_fg: g2,
            footer_key_fg: g3,
            footer_rule_color: g2,
            meter_on: g3,
            meter_off: g0,
            meter_hot: t.theme_label,
            meter_height: 8,
            chart_fill: g3,
            title_bg: "transparent",
            title_fg: g3,
            title_spacing: 0,
            chip_brackets: false,
            chip_active_bg: g3,
            chip_active_fg: g0,
            chip_pick: g3,
            chip_border: g2,
            toggle_on: g3,
            toggle_off: g2,
            marker_fill: false,
            bar_font_family: "Silkscreen",
            bar_font_size: 16,
            bar_side_bg: g1,
            bar_center_bg: g1,
            bar_fg: g3,
            bar_clock_fg: g3,
            bar_border_width: 2,
            bar_border_color: g0,
            bar_inset_gap: 0,
            bar_inset_width: 2,
            bar_inset_color: g2,
            bar_workspace_focused: g3,
            bar_workspace_active: g2,
            bar_workspace_idle: g0,
            bar_workspace_ring: g2,
            bar_pill_square: true,
            bar_hover_bg: Qt.alpha(g3, 0.25),
            small: {
                device_shell: true
            }
        }, colors);
    };
    const mono = [
        Qt.tint(t.bg_crust, Qt.alpha(t.theme_primary, 0.08)),
        Qt.tint(t.bg_core, Qt.alpha(t.theme_primary_strong, 0.34)),
        t.theme_primary,
        t.theme_primary_light
    ];
    const full = [t.bg_crust, t.bg_core, t.theme_primary, t.fg_strong];
    const colors = {
        text_muted: t.fg_muted,
        text_dim: t.fg_dim,
        text_fg: t.fg_core,
        text_primary: t.theme_primary,
        text_accent: t.theme_secondary,
        selection_bg: t.theme_primary,
        tab_active_bg: t.theme_primary,
        tab_fg: t.fg_dim,
        key_fg: t.theme_label,
        section_fg: t.theme_secondary,
        section_fade: t.theme_secondary,
        footer_fg: t.fg_dim,
        footer_key_fg: t.theme_label,
        meter_on: t.theme_primary,
        chart_fill: t.theme_primary,
        title_fg: t.theme_primary,
        chip_active_bg: t.theme_primary,
        chip_pick: t.theme_secondary,
        toggle_on: t.theme_primary,
        toggle_off: t.fg_dim,
        bar_fg: t.fg_core,
        bar_workspace_focused: t.theme_primary,
        bar_workspace_active: t.theme_secondary,
        bar_workspace_ring: t.theme_secondary
    };
    return Object.assign(build("color", full, colors), {
        models: { dmg: build("dmg", mono) },
        model_labels: { dmg: "Original", color: "Color" }
    });
}
