.pragma library
.import "../Watch.js" as Watch

// The pause watch for every popup: tinted from the palette, or the classic fixed colours (the watch_colors option).
function overrides(t, ctx) {
    return {
        osd_layout: "watch",
        workspace_art: "dial",
        wait_anim: "transmission",
        done_anim: "lcd",
        font_family: Watch.mono_font,
        title_font_family: Watch.head_font,
        number_font: Watch.digit_font,
        frame_border_width: 2,
        frame_radius: 10,
        frame_watch: true,
        link_style: "watch",
        ammo_counter: true,
        night_vision: true,
        toast_mission: true,
        track_bars: true,
        open_fx: "static",
        confirm_layout: "watch",
        lcd_margin: 8,
        picker_skin: "goldeneye",
        accent_height: 2,
        frame_top_rule: false,
        selection_outline: "transparent",
        selection_bar: false,
        caret_blink: false,
        row_cursor: "",
        tab_caps: true,
        section_rule: false,
        label_caps: true,
        label_spacing: 2,
        meter_hot: Watch.red,
        meter_slant: 0.4,
        meter_gap: 3,
        meter_height: 12,
        meter_palette: "bezel",
        chart_slant: 0.21,
        weather_header: "watch",
        title_bg: "transparent",
        title_spacing: 2,
        title_readout: "OASIS WATCH v" + ctx.version,
        chip_brackets: false,
        marker_fill: false,
        bar_font_family: "Michroma",
        bar_font_size: t.font_size - 1,
        bar_caps: true,
        bar_letter_spacing: 1.5,
        bar_side_bg: t.bg_crust,
        bar_center_bg: t.bg_crust,
        bar_border_color: Qt.tint(t.bg_crust, Qt.alpha(t.fg_muted, 0.5)),
        bar_hover_bg: Qt.tint(t.bg_crust, Qt.alpha(t.fg_muted, 0.25)),
        bar_separator: "tick",
        bar_island_shape: "octagon",
        bar_clock_font: Watch.digit_font,
        watch_colors: "Theme",
        watch_classic: ctx.classic_tokens
    };
}
