.pragma library

// Half-Life's VGUI windows and HEV HUD: dark panels on a primary hairline, Exo 2 text, Chakra Petch readouts.
function overrides(t, ctx) {
    const hl = t.theme_primary;
    const hl_t = Qt.alpha(hl, 0.72);
    const hl_l = Qt.alpha(hl, 0.55);
    const hl_hair = Qt.alpha(hl, 0.75);
    const hl_d = Qt.alpha(hl, 0.3);
    const hl_f = Qt.alpha(hl, 0.13);
    return {
        wait_anim: "hev_alert",
        done_anim: "hev_pickup",
        weather_header: "hev",
        osd_layout: "hud",
        text_muted: hl_t,
        text_dim: Qt.alpha(hl, 0.85),
        text_fg: hl,
        text_primary: hl,
        font_family: "Exo 2",
        font_size: t.popup_font_size + 2,
        number_font: "Chakra Petch",
        mono_font: "Chakra Petch",
        frame_color: t.bg_core,
        frame_border_color: hl_l,
        accent_color: hl,
        accent_height: 1,
        hairline: hl_hair,
        hairline_dim: hl_d,
        selection_bg: hl_f,
        selection_outline: "transparent",
        selection_border: hl_l,
        caret_color: hl,
        caret_blink: false,
        row_cursor: "",
        tab_active_bg: hl_f,
        tab_active_fg: t.fg_strong,
        tab_fg: hl_t,
        tab_underline: hl,
        tab_outline: hl_d,
        key_fg: t.theme_secondary,
        key_border: Qt.alpha(t.theme_secondary, 0.45),
        section_fg: hl,
        section_rule: false,
        section_fade: hl_d,
        label_spacing: 1,
        caps_tracking: 3,
        footer_fg: hl_t,
        footer_rule_solid: true,
        footer_rule_color: hl_d,
        meter_on: hl,
        meter_off: hl_f,
        title_bg: "transparent",
        title_fg: hl,
        title_spacing: 3.8,
        title_strip: hl_f,
        chip_brackets: false,
        chip_active_bg: hl,
        chip_active_fg: t.bg_crust,
        chip_pick: hl,
        chip_border: hl_l,
        toggle_brackets: false,
        toggle_on: hl,
        toggle_off: hl_t,
        marker_fill: false,
        bar_font_family: "Chakra Petch",
        bar_font_size: t.font_size + 1,
        bar_letter_spacing: 0.8,
        bar_side_bg: Qt.alpha(t.bg_core, 0.94),
        bar_center_bg: Qt.alpha(t.bg_core, 0.94),
        bar_fg: hl,
        bar_clock_fg: hl,
        bar_border_color: hl_l,
        bar_workspace_focused: t.theme_secondary,
        bar_workspace_active: hl,
        bar_workspace_idle: hl_f,
        bar_workspace_ring: hl_d,
        workspace_art: "squares",
        bar_pill_square: true,
        bar_hover_bg: hl_d
    };
}
