.pragma library

function overrides(t, ctx) {
    return {
        workspace_art: "doors",
        level_layout: "visor",
        wait_anim: "scan",
        weather_header: "scan",
        // Greys lifted toward primary_light so they read on the visor glass.
        text_muted: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.4)),
        text_dim: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.65)),
        font_family: "Share Tech Mono",
        font_size: t.popup_font_size + 1,
        // Meta and hint text at full size; the smallest labels stay a step down.
        type_scale: ({ "-1": 0, "-2": 0, "-3": -3, "-4": -3, "-5": -4, "-7": -5, "-8": -5 }),
        footer_size: 16,
        whichkey_size: 16,
        number_font: "Orbitron",
        rounded: true,
        frame_visor: true,
        frame_pad: 6,
        frame_color: t.bg_crust,
        frame_radius: 14,
        frame_border_width: 1,
        frame_border_color: Qt.alpha(t.theme_primary, 0.45),
        accent_color: t.theme_primary,
        accent_height: 0,
        selection_bg: Qt.alpha(t.theme_primary, 0.2),
        selection_outline: "transparent",
        selection_bar: true,
        fade_fills: true,
        caret_color: t.theme_secondary,
        caret_blink: false,
        row_cursor: "",
        tab_active_bg: Qt.alpha(t.theme_primary, 0.15),
        tab_active_fg: t.fg_strong,
        tab_fg: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.4)),
        key_fg: t.theme_secondary,
        key_border: Qt.alpha(t.theme_secondary, 0.45),
        section_fg: t.theme_primary,
        section_rule: false,
        section_fade: Qt.alpha(t.theme_primary, 0.5),
        label_caps: true,
        label_spacing: 2.5,
        footer_fg: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.4)),
        footer_rule: true,
        footer_compass: true,
        footer_rule_color: Qt.alpha(t.theme_primary, 0.35),
        title_reticle: Qt.alpha(t.theme_primary, 0.8),
        meter_off: Qt.alpha(t.theme_primary, 0.06),
        meter_radius: 1,
        meter_outline: Qt.alpha(t.theme_primary, 0.55),
        title_bg: "transparent",
        title_fg: t.theme_primary,
        title_spacing: 3,
        title_readout: "SCAN VISOR",
        title_readout_fg: t.theme_primary,
        picker_skin: "scanvisor",
        chip_brackets: false,
        chip_active_bg: t.theme_secondary,
        chip_active_fg: t.bg_crust,
        toggle_brackets: false,
        toggle_on: t.theme_primary,
        toggle_off: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.4)),
        bar_font_family: "Share Tech Mono",
        bar_font_size: 16,
        bar_side_bg: Qt.alpha(t.bg_crust, 0.95),
        bar_center_bg: Qt.alpha(t.bg_crust, 0.95),
        bar_fg: t.theme_primary_light,
        bar_border_color: Qt.alpha(t.theme_primary, 0.5),
        bar_workspace_idle: Qt.alpha(t.theme_primary, 0.18),
        bar_hover_bg: Qt.alpha(t.theme_primary, 0.18),
        small: {
            title_readout: "COMBAT VISOR"
        }
    };
}
