.pragma library
.import QtQuick as QtQuick

// Layered surfaces in Geist: floating cards, one segmented tab control, primary gradient selection.
function overrides(t, ctx) {
    const t1 = t.fg_strong;
    const t2 = Qt.tint(t.bg_mantle, Qt.alpha(t.fg_core, 0.74));
    const t3 = Qt.tint(t.bg_mantle, Qt.alpha(t.fg_core, 0.5));
    const l0 = Qt.tint(t.bg_core, Qt.alpha(t.bg_mantle, 0.78));
    const l1 = Qt.tint(t.bg_mantle, Qt.alpha(t.bg_surface, 0.62));
    const l2 = Qt.tint(t.bg_surface, Qt.alpha(t.ui_visual_bg, 0.55));
    const raised = Qt.tint(t.bg_mantle, Qt.alpha(t.bg_surface, 0.72));
    const well = Qt.tint(t.bg_mantle, Qt.alpha(t.bg_core, 0.72));
    const edge = Qt.alpha(t.fg_strong, 0.07);
    const hi = Qt.alpha(t.fg_strong, 0.13);
    const accent_top = Qt.tint(t.theme_primary_light, Qt.alpha(t.theme_primary, 0.82));
    const accent = t.theme_primary_strong;
    return {
        text_muted: t3,
        text_dim: t2,
        text_fg: t1,
        text_strong: t1,
        text_primary: t.theme_primary,
        text_accent: t.theme_secondary,
        font_family: "Geist",
        font_size: t.popup_font_size + 1,
        type_scale: ({ "-1": 0, "-2": 0, "-3": -3, "-4": -3, "-5": -4, "-7": -5, "-8": -5 }),
        footer_size: 16,
        whichkey_size: 16,
        number_font: "Geist Mono",
        mono_font: "Geist Mono",
        scale: 1.1,
        rounded: true,
        corner_scale: 1.75,
        frame_color: l0,
        frame_shade: l1,
        shade_vertical: true,
        frame_radius: 22,
        frame_border_width: 1,
        frame_border_color: edge,
        frame_pad: 8,
        frame_drop: 14,
        frame_float: 6,
        frame_shadow: Qt.alpha(t.bg_crust, 0.6),
        sheen: hi,
        accent_color: t.theme_primary,
        accent_height: 0,
        selection_bg: accent,
        selection_shade: accent_top,
        selection_inverse: true,
        selection_fg: t.bg_crust,
        selection_outline: "transparent",
        caret_color: t.theme_primary,
        caret_blink: false,
        row_cursor: "",
        tab_well: well,
        tab_active_bg: raised,
        tab_active_shade: l2,
        tab_active_fg: t1,
        tab_fg: t2,
        tab_key_plain: true,
        key_bg: l2,
        key_fg: t2,
        key_border: edge,
        section_fg: t3,
        section_rule: false,
        footer_fg: t3,
        footer_key_fg: t2,
        footer_key_bg: l2,
        footer_rule_solid: true,
        footer_rule_color: edge,
        meter_on: t.theme_primary,
        meter_shade: t.theme_primary_light,
        meter_off: well,
        meter_hot: t.theme_label,
        meter_radius: 2,
        meter_height: 8,
        chart_fill: t.theme_primary,
        title_bg: "transparent",
        title_fg: t1,
        title_spacing: -0.2,
        title_weight: QtQuick.Font.DemiBold,
        title_case: true,
        title_status: true,
        title_size: t.popup_font_size,
        row_keys: false,
        boxed_cards: false,
        chip_brackets: false,
        chip_active_bg: raised,
        chip_active_fg: t1,
        chip_pick: accent,
        chip_fg: t1,
        toggle_brackets: false,
        toggle_on: t.theme_primary,
        toggle_off: t3,
        marker_fill: false,
        osd_layout: "tile",
        level_layout: "capsule",
        card_layout: "tile",
        weather_header: "hero",
        bar_font_family: "Geist",
        bar_font_size: t.font_size,
        bar_side_bg: l0,
        bar_center_bg: l0,
        bar_fg: t1,
        bar_clock_fg: t1,
        bar_border_width: 1,
        bar_border_color: edge,
        bar_rounded: true,
        bar_capsule: 5,
        bar_capsule_pad: 14,
        bar_height: 40,
        bar_module_gap: 22,
        bar_pill_height: 26,
        bar_pill_pad: 3,
        bar_workspace_gap: 10,
        bar_clock_layout: "capsule",
        bar_start_well: well,
        bar_workspace_focused: accent,
        bar_workspace_shade: accent_top,
        bar_workspace_active: Qt.alpha(t.theme_primary, 0.35),
        bar_workspace_idle: Qt.tint(t.bg_mantle, Qt.alpha(t.bg_surface, 0.8)),
        bar_workspace_dot: Qt.alpha(t.fg_core, 0.26),
        bar_workspace_ring: "transparent",
        bar_hover_bg: Qt.alpha(t.fg_strong, 0.08),
        small: {
            frame_radius: 18
        }
    };
}
