.pragma library

// Modern Neovim: lualine bar, floating windows with border titles, telescope rows, which-key footers, nvim-notify cards.
function overrides(t, ctx) {
    const float_border = Qt.tint(t.bg_mantle, Qt.alpha(t.theme_primary, 0.6));
    return {
        workspace_art: "buffers",
        weather_header: "lsp",
        card_layout: "notify",
        wait_anim: "cursor",
        font_family: "Maple Mono NF",
        // One 16px scale like the notification panel: -1/-2 text is primary, -3/-4 meta, -5 and smaller tags.
        font_size: t.popup_font_size + 1,
        type_scale: ({ "-1": 0, "-2": 0, "-3": -4, "-5": -6, "-7": -6, "-8": -6 }),
        scale: 1.1,
        rounded: false,
        border_title: true,
        title_case: true,
        title_status: true,
        picker_skin: "nvimfloat",
        picker_hint_keys: "asfgzxcvbnwertyuiop",
        picker_hud: t.theme_primary,
        frame_color: t.bg_mantle,
        frame_radius: 8,
        frame_border_width: 1,
        frame_border_color: float_border,
        accent_color: t.theme_primary,
        accent_height: 0,
        selection_bg: t.bg_surface,
        selection_outline: "transparent",
        selection_bar: true,
        caret_color: t.theme_primary,
        caret_blink: false,
        row_cursor: "",
        row_gutter: true,
        row_keys: false,
        tab_bg: t.bg_crust,
        tab_active_bg: t.theme_secondary,
        tab_active_fg: t.bg_core,
        tab_fg: t.fg_dim,
        tab_marker: t.theme_secondary,
        key_bg: "transparent",
        key_fg: t.theme_secondary,
        key_border: "transparent",
        section_fg: t.theme_primary,
        section_rule: false,
        section_fold: true,
        footer_fg: t.fg_dim,
        footer_key_fg: t.theme_secondary,
        footer_rule: true,
        footer_rule_solid: true,
        footer_rule_color: t.bg_surface,
        footer_separator: "",
        footer_arrow: "",
        footer_italic: true,
        footer_size: 16,
        whichkey_arrow: "\u279c",
        whichkey_size: 16,
        meter_on: t.theme_primary,
        meter_off: t.bg_surface,
        meter_hot: t.theme_label,
        meter_radius: 0,
        meter_height: 4,
        meter_gap: 1,
        title_bg: t.theme_primary,
        title_fg: t.bg_crust,
        title_spacing: 0,
        chip_brackets: false,
        chip_active_bg: t.ui_visual_bg,
        chip_active_fg: t.fg_strong,
        chip_pick: t.theme_primary,
        chip_border: t.bg_surface,
        toggle_brackets: false,
        toggle_on: t.ok,
        toggle_off: t.fg_dim,
        bar_lualine: true,
        bar_font_family: "Maple Mono NF",
        // Sized like the tmux status line in kitty: Maple Mono at 12pt.
        bar_font_size: 16,
        bar_glyph_size: 16,
        bar_clock_size: 16,
        bar_height: 24,
        bar_side_bg: t.bg_surface,
        bar_center_bg: t.bg_surface,
        bar_fg: t.fg_core,
        bar_clock_fg: t.fg_strong,
        bar_border_width: 0,
        bar_border_color: "transparent",
        bar_workspace_focused: t.theme_primary,
        bar_workspace_active: t.theme_secondary,
        bar_workspace_idle: t.fg_muted,
        // LualineSection lights hovered components itself.
        bar_hover_bg: "transparent"
    };
}
