.pragma library

function overrides(t, ctx) {
    return {
        wait_anim: "advance",
        done_anim: "pixel",
        weather_header: "battle",
        text_muted: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.35)),
        text_dim: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.6)),
        // Press Start 2P draws on an 8px grid and runs 1em wide; 14 sits between its 1.5x and 2x sizes, with a wider frame.
        font_family: "Press Start 2P",
        font_size: 14,
        // Press Start 2P is wide and has no leading, so fs(-5) and fs(-4) shrink keys past legible.
        key_size: 12,
        footer_size: 12,
        scale: 1.2,
        popup_min_width: 295,
        frame_color: t.bg_crust,
        frame_border_width: 0,
        frame_border_color: "transparent",
        frame_inset_gap: 4,
        frame_inset_width: 3,
        frame_inset_color: t.fg_strong,
        accent_color: t.theme_primary,
        accent_height: 4,
        selection_bg: "transparent",
        selection_outline: "transparent",
        caret_color: t.theme_primary,
        row_cursor: "\u25b6",
        tab_active_bg: t.theme_primary,
        tab_active_fg: t.bg_crust,
        tab_fg: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.35)),
        key_bg: "transparent",
        key_fg: t.theme_secondary,
        key_border: "transparent",
        section_fg: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.35)),
        section_rule: false,
        footer_fg: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.35)),
        footer_rule: false,
        meter_on: t.theme_primary,
        meter_off: t.bg_surface,
        meter_hot: t.theme_label,
        meter_radius: 0,
        title_bg: "transparent",
        title_fg: t.theme_primary,
        chip_brackets: false,
        chip_active_bg: t.theme_primary,
        chip_active_fg: t.bg_crust,
        toggle_on: t.theme_primary,
        toggle_off: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.35)),
        bar_font_family: "Press Start 2P",
        bar_font_size: 14,
        bar_side_bg: t.bg_crust,
        bar_center_bg: t.bg_crust,
        bar_fg: t.fg_strong,
        bar_border_width: 0,
        bar_border_color: "transparent",
        bar_inset_gap: 2,
        bar_inset_width: 2,
        bar_inset_color: t.fg_strong,
        scanlines: true,
        scanline_color: Qt.alpha(t.bg_shadow, 0.12),
        scanline_period: 2,
        bar_scanline_color: Qt.alpha(t.bg_shadow, 0.08),
        card_layout: "dq",
        controller: "nes",
        console_views: "nes",
        toast_enter: "type",
        picker_skin: "duckhunt",
        meter_art: ({ volume: "nes/HeartMeter.qml", battery: "nes/EnergyBar.qml", osd: "nes/EnergyBar.qml", media: "nes/PianoRoll.qml" })
    };
}
