.pragma library
.import QtQuick as QtQuick

// A desert oasis at night: night-blue panels, sand for selection and focus, slanted frames with a sand horizon and a crescent moon.
function overrides(t, ctx) {
    const sand = t.theme_secondary;
    const sky = Qt.tint(t.bg_mantle, Qt.alpha(t.ui_visual_bg, 0.72));
    const rim = Qt.tint(t.bg_mantle, Qt.alpha(t.theme_primary_light, 0.4));
    const edge = Qt.tint(t.bg_core, Qt.alpha(t.theme_primary, 0.28));
    const hair = Qt.alpha(t.theme_primary, 0.3);
    const well = Qt.alpha(t.bg_crust, 0.55);
    const t2 = Qt.tint(t.fg_core, Qt.alpha(t.theme_primary_light, 0.28));
    return {
        workspace_art: "constellation",
        bar_clock_layout: "horizon",
        weather_header: "oasis",
        osd_layout: "horizon",
        level_layout: "slant",
        card_layout: "oasis",
        text_muted: t.fg_dim,
        text_dim: t2,
        text_fg: t2,
        text_strong: t.fg_strong,
        text_primary: t.theme_primary_light,
        text_accent: sand,
        font_family: "Inter",
        font_size: t.popup_font_size + 1,
        type_scale: ({ "-1": 0, "-2": 0, "-3": -3, "-4": -3, "-5": -4, "-7": -5, "-8": -5 }),
        scale: 1,
        number_font: "Inter",
        mono_font: "JetBrainsMono Nerd Font",
        rounded: true,
        corner_scale: 2,
        frame_color: t.bg_core,
        frame_shade: sky,
        shade_vertical: true,
        frame_radius: 0,
        frame_border_width: 1,
        frame_border_color: edge,
        accent_color: rim,
        accent_height: 1,
        accent_full_width: false,
        sheen: Qt.alpha(t.theme_primary_light, 0.34),
        selection_bg: Qt.alpha(sand, 0.16),
        selection_outline: "transparent",
        selection_edge: sand,
        fade_fills: true,
        caret_color: sand,
        caret_blink: false,
        row_cursor: "",
        tab_well: well,
        chip_tabs: true,
        tab_marker: sand,
        tab_active_shade: t.bg_surface,
        tab_active_bg: Qt.tint(t.bg_mantle, Qt.alpha(t.bg_surface, 0.55)),
        tab_active_fg: t.fg_strong,
        tab_fg: t.fg_dim,
        key_bg: Qt.alpha(sand, 0.1),
        key_fg: sand,
        key_border: Qt.alpha(sand, 0.22),
        section_fg: t.theme_primary,
        section_rule: false,
        section_fade: hair,
        slant_frame: true,
        footer_moon: true,
        label_caps: false,
        caps_tracking: 0,
        footer_fg: t.fg_dim,
        footer_key_fg: sand,
        footer_key_bg: Qt.alpha(sand, 0.1),
        footer_rule: true,
        footer_rule_solid: true,
        footer_rule_color: hair,
        meter_on: t.theme_primary_light,
        meter_off: Qt.alpha(t.theme_primary, 0.14),
        meter_hot: t.theme_label,
        meter_radius: 2,
        meter_height: 6,
        chart_fill: t.theme_primary_light,
        title_bg: "transparent",
        title_fg: t.fg_strong,
        title_spacing: 0,
        title_weight: QtQuick.Font.DemiBold,
        title_case: true,
        title_size: t.popup_font_size + 1,
        boxed_cards: false,
        chip_brackets: false,
        chip_bg: Qt.alpha(t.theme_primary, 0.1),
        chip_active_bg: Qt.alpha(sand, 0.16),
        chip_active_fg: t.fg_strong,
        chip_pick: sand,
        chip_border: edge,
        toggle_brackets: false,
        toggle_on: sand,
        toggle_off: t.fg_dim,
        marker_fill: false,
        bar_font_family: "Inter",
        bar_font_size: 16,
        whichkey_size: 16,
        footer_size: 16,
        bar_side_bg: t.bg_core,
        bar_center_bg: t.bg_core,
        bar_fg: t2,
        bar_clock_fg: t.fg_strong,
        bar_border_width: 1,
        bar_border_color: edge,
        bar_rounded: true,
        bar_workspace_focused: sand,
        bar_workspace_active: t.theme_primary_light,
        bar_workspace_idle: t.bg_surface,
        bar_workspace_ring: "transparent",
        bar_hover_bg: Qt.alpha(t.theme_primary_light, 0.1)
    };
}
