.pragma library

function overrides(t, ctx) {
    return {
        controller: "ps1",
        toast_enter: "wobble",
        console_views: "ps1",
        osd_layout: "alert",
        wait_anim: "alert",
        done_anim: "pixel",
        weather_header: "memcard",
        picker_skin: "scope",
        overview_skin: "scope",
        picker_hud: Qt.tint(t.green, Qt.alpha(t.theme_secondary, 0.35)),
        // Muted text brightened; the shaded, dithered frame swallows the theme greys.
        text_muted: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.35)),
        text_dim: Qt.tint(t.fg_dim, Qt.alpha(t.fg_core, 0.6)),
        font_family: "Terminess Nerd Font",
        font_size: t.popup_font_size + 7,
        frame_color: t.bg_crust,
        frame_shade: t.bg_mantle,
        frame_radius: 10,
        frame_border_width: 2,
        frame_border_color: t.fg_dim,
        accent_color: t.theme_primary,
        selection_bg: Qt.alpha(t.theme_primary, 0.35),
        selection_outline: "transparent",
        fade_fills: true,
        caret_color: t.theme_primary_light,
        row_cursor: "◆",
        tab_active_bg: Qt.alpha(t.theme_primary, 0.35),
        tab_active_fg: t.fg_strong,
        tab_fg: t.theme_primary_light,
        key_fg: t.theme_secondary,
        key_border: "transparent",
        section_fg: t.theme_primary_light,
        section_rule: false,
        footer_fg: t.theme_primary_light,
        footer_rule: false,
        meter_shade: t.theme_primary_light,
        meter_off: t.bg_shadow,
        title_bg: Qt.alpha(t.theme_primary, 0.3),
        title_fg: t.fg_strong,
        chip_brackets: false,
        chip_active_bg: Qt.alpha(t.theme_primary, 0.35),
        chip_active_fg: t.fg_strong,
        dither: Qt.alpha(t.bg_shadow, 0.22),
        text_shadow: t.bg_shadow,
        bar_font_family: "Terminess Nerd Font",
        bar_font_size: t.font_size + 4,
        bar_side_bg: t.bg_core,
        bar_center_bg: t.bg_mantle,
        bar_border_color: t.fg_dim,
        bar_workspace_idle: Qt.alpha(t.fg_dim, 0.35),
        bar_hover_bg: Qt.alpha(t.theme_primary, 0.35),
        bar_glow_color: t.bg_shadow,
        bar_text_raised: true
    };
}
