.pragma library

function overrides(t, ctx) {
    return {
        wait_anim: "rumble",
        weather_header: "towers",
        done_anim: "pixel",
        // Muted text lifted so it still reads on the lit selection pill.
        text_muted: Qt.tint(t.fg_muted, Qt.alpha(t.theme_primary_light, 0.35)),
        text_dim: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.3)),
        font_family: "Exo 2",
        font_size: t.popup_font_size + 3,
        rounded: true,
        corner_scale: 2.5,
        frame_color: t.bg_mantle,
        frame_radius: 14,
        frame_border_width: 0,
        frame_border_color: "transparent",
        accent_color: t.theme_primary,
        accent_height: 2,
        selection_bg: Qt.alpha(t.theme_primary, 0.14),
        selection_outline: "transparent",
        selection_border: Qt.alpha(t.theme_primary_light, 0.35),
        selection_glow: Qt.alpha(t.theme_primary, 0.35),
        caret_color: t.theme_primary_light,
        caret_blink: false,
        row_cursor: "",
        tab_active_bg: Qt.alpha(t.theme_primary, 0.14),
        tab_active_fg: t.fg_strong,
        tab_fg: t.theme_primary_light,
        key_fg: t.theme_primary,
        key_border: Qt.alpha(t.theme_primary, 0.4),
        section_fg: t.theme_primary,
        section_rule: false,
        footer_fg: t.theme_primary_strong,
        footer_rule: false,
        meter_shade: t.theme_primary_light,
        meter_off: Qt.alpha(t.theme_primary, 0.1),
        meter_radius: 2,
        title_bg: "transparent",
        title_fg: t.fg_strong,
        chip_brackets: false,
        chip_active_bg: Qt.alpha(t.theme_primary, 0.14),
        chip_active_fg: t.fg_strong,
        toggle_brackets: false,
        toggle_on: t.theme_primary,
        toggle_off: t.fg_dim,
        marker_fill: false,
        bar_font_family: "Exo 2",
        bar_font_size: t.font_size + 2,
        bar_side_bg: t.bg_mantle,
        bar_center_bg: t.bg_mantle,
        bar_fg: t.theme_primary_light,
        bar_border_width: 0,
        bar_border_color: "transparent",
        bar_rounded: true,
        bar_workspace_idle: Qt.alpha(t.theme_primary, 0.12),
        bar_hover_bg: Qt.alpha(t.theme_primary, 0.2),
        frame_shade: Qt.tint(t.bg_mantle, Qt.alpha(t.theme_primary, 0.14)),
        shade_vertical: true,
        bar_inset_gap: 2,
        bar_inset_width: 1,
        bar_inset_color: Qt.alpha(t.theme_primary_light, 0.22),
        card_layout: "dialog",
        osd_layout: "glow",
        controller: "ps2",
        console_views: "ps2",
        workspace_art: "ps2",
        toast_enter: "bloom",
        picker_skin: "scopeitem"
    };
}
