.pragma library
.import QtQuick as QtQuick

// A sci-fi targeting display: pale hairlines on near-black, thin caps, tick scales and ring gauges.
function overrides(t, ctx) {
    return {
        wait_anim: "ping",
        text_muted: Qt.alpha(t.fg_strong, 0.55),
        text_dim: Qt.alpha(t.fg_strong, 0.7),
        text_fg: Qt.alpha(t.fg_strong, 0.86),
        text_strong: t.fg_strong,
        text_primary: t.theme_primary_light,
        text_accent: t.theme_primary_light,
        font_family: "Jura",
        font_size: t.popup_font_size + 2,
        title_font_family: "Jura",
        number_font: "Saira",
        scale: 1.1,
        frame_color: Qt.alpha(t.bg_crust, 0.97),
        frame_shade: Qt.alpha(t.bg_core, 0.97),
        shade_vertical: true,
        frame_border_width: 0,
        frame_border_color: Qt.alpha(t.fg_strong, 0.24),
        frame_pad: 10,
        accent_color: Qt.alpha(t.fg_strong, 0.55),
        accent_height: 1,
        frame_top_rule: true,
        hairline: Qt.alpha(t.fg_strong, 0.55),
        hairline_dim: Qt.alpha(t.fg_strong, 0.24),
        frame_ticks: "top",
        selection_bg: Qt.alpha(t.theme_primary_light, 0.14),
        selection_outline: "transparent",
        selection_rule: Qt.alpha(t.theme_primary_light, 0.6),
        fade_fills: true,
        caret_color: t.theme_primary_light,
        caret_blink: false,
        row_cursor: "○",
        tab_active_bg: "transparent",
        tab_active_fg: t.fg_strong,
        tab_fg: Qt.alpha(t.fg_strong, 0.55),
        tab_caps: true,
        tab_underline: t.fg_strong,
        tab_rule: Qt.alpha(t.fg_strong, 0.12),
        key_fg: t.theme_primary_light,
        key_border: Qt.alpha(t.fg_strong, 0.24),
        key_round: true,
        section_fg: Qt.alpha(t.fg_strong, 0.55),
        section_rule: false,
        section_fade: Qt.alpha(t.fg_strong, 0.18),
        label_caps: true,
        label_spacing: 3,
        footer_fg: Qt.alpha(t.fg_strong, 0.55),
        footer_key_fg: t.theme_primary_light,
        footer_rule_color: Qt.alpha(t.fg_strong, 0.18),
        meter_on: t.fg_strong,
        meter_off: Qt.alpha(t.fg_strong, 0.1),
        meter_hot: t.theme_label,
        tick_ruler: true,
        title_bg: "transparent",
        title_fg: t.fg_strong,
        title_spacing: 5,
        title_weight: QtQuick.Font.Light,
        title_index: ["start", "volume", "notifications", "weather", "media", "clock", "battery", "network", "bluetooth", "system", "updates", "tray", "keeptabs", "settings"],
        title_trail: Qt.alpha(t.fg_strong, 0.24),
        title_readout: "TET · LINK",
        title_readout_fg: Qt.alpha(t.fg_strong, 0.55),
        chip_brackets: false,
        chip_active_bg: t.fg_strong,
        chip_active_fg: t.bg_crust,
        chip_pick: t.fg_strong,
        chip_border: Qt.alpha(t.fg_strong, 0.24),
        pill_chips: true,
        card_layout: "rule",
        toggle_brackets: false,
        toggle_on: t.fg_strong,
        toggle_off: Qt.alpha(t.fg_strong, 0.55),
        marker_fill: false,
        osd_layout: "ring",
        weather_header: "ring",
        range_line: true,
        bar_font_family: "Jura",
        bar_font_size: t.font_size + 1,
        bar_letter_spacing: 1.5,
        bar_side_bg: Qt.alpha(t.bg_core, 0.85),
        bar_center_bg: Qt.alpha(t.bg_core, 0.85),
        bar_fg: Qt.alpha(t.fg_strong, 0.86),
        bar_clock_fg: Qt.alpha(t.fg_strong, 0.86),
        bar_border_color: Qt.alpha(t.fg_strong, 0.24),
        bar_workspace_focused: t.fg_strong,
        bar_workspace_active: Qt.alpha(t.theme_secondary, 0.45),
        bar_workspace_idle: "transparent",
        bar_workspace_ring: Qt.alpha(t.fg_strong, 0.55),
        bar_hover_bg: Qt.alpha(t.fg_strong, 0.08),
        bar_ticks: Qt.alpha(t.fg_strong, 0.24),
        small: {
            frame_ticks: "left",
            frame_color: Qt.alpha(t.bg_core, 0.96),
            frame_shade: "transparent",
            frame_border_width: 1,
            accent_color: Qt.alpha(t.fg_strong, 0.24),
            frame_pad: 6,
            title_readout: ""
        }
    };
}
