.pragma library

function overrides(t, ctx) {
    return {
        wait_anim: "hand",
        done_anim: "pixel",
        weather_header: "mode7",
        controller: "snes",
        console_views: "snes",
        osd_layout: "rpg",
        card_layout: "dialogue",
        toast_enter: "mode7",
        picker_skin: "jrpg",
        // Greys lifted toward primary_light so they read on the shaded window.
        text_muted: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.4)),
        text_dim: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.65)),
        // Silkscreen sits on an 8px grid; 16 is its 2x size.
        font_family: "Silkscreen",
        font_size: 16,
        frame_color: t.bg_crust,
        frame_shade: t.bg_mantle,
        shade_vertical: true,
        frame_radius: 6,
        frame_border_width: 3,
        frame_border_color: t.theme_primary,
        frame_inset_width: 2,
        frame_inset_color: t.fg_muted,
        frame_drop: 4,
        accent_color: t.theme_secondary,
        accent_height: 4,
        selection_bg: Qt.alpha(t.fg_strong, 0.12),
        selection_outline: "transparent",
        caret_color: t.theme_secondary,
        caret_blink: false,
        row_cursor: "\uf0a4",
        tab_active_bg: Qt.alpha(t.fg_strong, 0.12),
        tab_active_fg: t.theme_secondary,
        tab_fg: t.theme_primary_light,
        key_fg: t.theme_secondary,
        key_border: "transparent",
        section_fg: t.theme_primary_light,
        section_rule: false,
        footer_fg: t.theme_primary_light,
        footer_rule: false,
        meter_shade: t.theme_primary_light,
        meter_radius: 1,
        title_bg: "transparent",
        title_fg: t.theme_secondary,
        chip_brackets: false,
        chip_active_bg: Qt.alpha(t.fg_strong, 0.12),
        chip_active_fg: t.theme_secondary,
        toggle_brackets: false,
        toggle_on: t.theme_secondary,
        toggle_off: Qt.tint(t.fg_dim, Qt.alpha(t.theme_primary_light, 0.65)),
        text_shadow: t.bg_shadow,
        scanlines: true,
        scanline_color: Qt.alpha(t.bg_shadow, 0.12),
        scanline_period: 2,
        bar_scanline_color: Qt.alpha(t.bg_shadow, 0.08),
        bar_font_family: "Silkscreen",
        bar_font_size: 16,
        bar_side_bg: t.bg_core,
        bar_center_bg: t.bg_core,
        bar_border_width: 2,
        bar_border_color: t.theme_primary,
        bar_workspace_idle: t.bg_mantle,
        bar_workspace_ring: t.theme_primary,
        bar_hover_bg: Qt.alpha(t.theme_primary, 0.3),
        bar_glow_color: t.bg_shadow,
        bar_text_raised: true
    };
}
