.pragma library

// TIE Fighter cockpit: large popups in the octagonal viewport, `small` ones the targeting computer.
function overrides(t, ctx) {
    const vec = t.ok;
    const vec_d = Qt.alpha(vec, 0.4);
    const lock = t.theme_label;
    return {
        wait_anim: "comms",
        picker_skin: "tiecomp",
        text_muted: Qt.alpha(vec, 0.55),
        text_dim: Qt.alpha(vec, 0.7),
        text_fg: Qt.tint(t.fg_core, Qt.alpha(vec, 0.72)),
        text_strong: t.fg_strong,
        text_primary: vec,
        text_accent: t.theme_secondary,
        font_family: "B612 Mono",
        font_size: t.popup_font_size - 1,
        title_font_family: "Oxanium",
        label_font_family: "Oxanium",
        number_font: "Oxanium",
        frame_color: t.bg_crust,
        frame_shade: t.bg_mantle,
        shade_vertical: true,
        frame_border_color: vec,
        frame_octagon: 20,
        frame_struts: vec,
        frame_pad: 12,
        accent_color: vec,
        accent_height: 0,
        selection_bg: Qt.alpha(lock, 0.08),
        selection_outline: "transparent",
        selection_brackets: lock,
        caret_color: lock,
        caret_blink: false,
        row_cursor: "\u25b8",
        tab_active_bg: Qt.alpha(vec, 0.09),
        tab_active_fg: t.fg_strong,
        tab_fg: Qt.alpha(vec, 0.55),
        tab_caps: true,
        tab_underline: vec,
        tab_brackets: lock,
        tab_rule: vec_d,
        key_fg: t.theme_secondary,
        key_border: Qt.alpha(t.theme_secondary, 0.45),
        section_fg: vec,
        section_rule: false,
        section_fade: vec_d,
        label_caps: true,
        label_spacing: 2.5,
        footer_fg: Qt.alpha(vec, 0.55),
        footer_rule_color: vec_d,
        meter_on: Qt.alpha(vec, 0.75),
        meter_off: Qt.alpha(vec, 0.1),
        meter_hot: lock,
        meter_bloom: true,
        title_bg: "transparent",
        title_fg: vec,
        title_spacing: 3.5,
        title_readout: "SCAN",
        title_readout_fg: t.theme_secondary,
        title_reticle: vec,
        title_trail: vec_d,
        chip_brackets: false,
        chip_active_bg: lock,
        chip_active_fg: t.bg_crust,
        chip_pick: lock,
        chip_border: vec_d,
        toggle_on: vec,
        toggle_off: Qt.alpha(vec, 0.45),
        scanlines: true,
        scanline_color: Qt.alpha(vec, 0.05),
        chart_fill: Qt.alpha(vec, 0.09),
        chart_outline: vec,
        weather_header: "scope",
        bar_font_family: "B612 Mono",
        bar_font_size: t.font_size - 1,
        bar_side_bg: t.bg_crust,
        bar_center_bg: t.bg_crust,
        bar_fg: vec,
        bar_border_color: vec,
        bar_workspace_focused: t.theme_secondary,
        bar_workspace_active: vec,
        bar_workspace_idle: "transparent",
        bar_workspace_ring: vec,
        bar_workspace_diamond: true,
        bar_pill_square: true,
        bar_clock_brackets: lock,
        bar_hover_bg: Qt.alpha(vec, 0.15),
        small: {
            frame_octagon: 0,
            frame_radius: 5,
            frame_border_color: t.bg_surface,
            frame_pad: 0,
            lcd_top: Qt.tint(t.bg_core, Qt.alpha(vec, 0.06)),
            lcd_bottom: t.bg_crust,
            lcd_scan: Qt.alpha(vec, 0.05),
            lcd_margin: 9,
            lcd_radius: 16,
            lcd_border: vec_d,
            lcd_brackets: vec,
            scanlines: false,
            title_readout: "TRGT CMP"
        }
    };
}
