--- Submap keybinds

require("keymaps.submaps.apps")
require("keymaps.submaps.ai")
require("keymaps.submaps.go")
require("keymaps.submaps.system")
require("keymaps.submaps.delete")
require("keymaps.submaps.swaync")
require("keymaps.submaps.screenshot")
require("keymaps.submaps.windows")
require("keymaps.submaps.cursor")
require("keymaps.submaps.resize")
require("keymaps.submaps.move")
require("keymaps.submaps.zoom")
require("keymaps.submaps.marks")
