# hypr/.config/hypr/hyprlock.conf
# VARIABLES
$font = ProFont IIx Nerd Font Mono
$font_italic = Maple Mono
$hex_primary = #42A5F5
$primary = rgb(42A5F5)

$hex_primary_light = #94D0FE
$primary_light = rgb(#94D0FE)

$hex_accent= #FEA147
$accent = rgb(FEA147)

$hex_accent2 = #F0E68C
$accent2 = rgb(F0E68C)

$hex_error = #CC5F5F
$error = rgb(CC5F5F)

$hex_warning = #FFA0A0
$warning = rgb(FFA0A0)

$hex_bg_core = #101825
$bg_core = rgb(101825)
$bg_core_faded = rgba(10182599)

$hex_bg_mantle = #1A283F
$bg_mantle = rgb(1A283F)

$hex_bg_surface = #22385C
$bg_surface = rgb(22385C)

$hex_fg_core = #d9e6fa
$fg_core = rgb(D9E6FA)
$fg_core_faded = rgba(D9E6FA99)

# MONITORS
$MON_LAPTOP = desc:BOE 0x0C8E
$MON_LEFT = desc:HP Inc. HP Z22n G2 6CM8411J1Z
$MON_CENTER = desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27QC A 0x00000D48
$MON_RIGHT = desc:HP Inc. HP Z22n G2 6CM8411J22

# GENERAL
general {
  hide_cursor = true
  ignore_empty_input = true # skip validation when no input provided
  screencopy_mode = 0 # 0: gpu accelerated, 1: cpu based
  immediate_render = true # immediately draw widgets
}

# BACKGROUNDS
background {
  monitor = $MON_LAPTOP
  path = $HOME/.cache/hyprlock/Laptop.png
  blur_passes = 1
  color = $bg_core_faded
}

background {
  monitor = $MON_LEFT
  path = $HOME/.cache/hyprlock/Left.png
  blur_passes = 1
  color = $bg_core_faded
}

background {
  monitor = $MON_CENTER
  path = $HOME/.cache/hyprlock/Center.png
  blur_passes = 1
  color = $bg_core_faded
}

background {
  monitor = $MON_RIGHT
  path = $HOME/.cache/hyprlock/Right.png
  blur_passes = 1
  color = $bg_core_faded
}

# Date/Time Top Right
# # TIME
# label {
#   monitor =
#   text = $TIME
#   color = $fg_core
#   font_size = 90
#   font_family = $font
#   position = -30, 0
#   halign = right
#   valign = top
# }
#
# # DATE
# label {
#   monitor =
#   text = cmd[update:43200000] date +"%A, %d %B %Y"
#   color = $fg_core
#   font_size = 25
#   font_family = $font
#   position = -30, -160
#   halign = right
#   valign = top
# }

# DAY
label {
  monitor =
  # text = cmd[update:1000] echo -e "<span font_variant='small-caps'><b>$(date +"%A")</b></span>"
  text = cmd[update:1000] echo -e "<span font_variant='small-caps'>$(date +"%A")</span>"
  color = $fg_core
  font_size = 125
  font_family = $font
  position = 0, 0
  halign = center
  valign = top
  # shadow_passes = 1
}

# TIME
label {
  monitor =
  text = <span><b>$TIME</b></span>
  color = $primary
  font_size = 70
  font_family = $font
  position = 0, -180
  halign = center
  valign = top
  # shadow_passes = 1
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo -e "<span>$(date +"%B %d %Y")</span>"
  color = $fg_core
  font_size = 20
  font_family = $font
  position = 0, -300
  halign = center
  valign = top
  # shadow_passes = 1
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_size = 0
  border_color = $primary
  position = 0, 75
  halign = center
  valign = center
}

# USER NAME
label {
  monitor =
  text = $USER
  color = $primary
  font_size = 25
  font_family = $font
  position = 0, -10
  halign = center
  valign = center
  # shadow_passes = 1
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  rounding = 4
  outline_thickness = 1
  dots_size = 0.4
  dots_spacing = 0.2
  dots_center = true
  dots_text_format = 󱍿
  # dots_text_format = 󰓥  󰣙  󰮯 󰸳  󱍿
  outer_color = $accent
  inner_color = $bg_core_faded
  font_color = $fg_core
  font_family = $font
  fade_on_empty = false
  placeholder_text = <span foreground="##F0E68C">󰌾 </span><span foreground="##d9e6fa">Enter Password<span size="small">...</span></span>
  hide_input = false
  check_color = $primary
  fail_color = $error
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $warning
  position = 0, -80
  halign = center
  valign = center
}
