git:
  diffRenderers:
    - type: extDiff
      command: difft --color=always --background=dark --display=inline --context={{diffContext}}
    - type: rawGit
      name: default
gui:
  showRandomTip: false
  showCommandLog: false
  theme:
    activeBorderColor:
      - "#CDC673"
      - bold
    inactiveBorderColor:
      - "#7FA3C9"
    optionsTextColor:
      - "#F0E68C"
    selectedLineBgColor:
      - "#1A2330"
    cherryPickedCommitBgColor:
      - "#1A2330"
    cherryPickedCommitFgColor:
      - "#7FA3C9"
    unstagedChangesColor:
      - "#FF7979"
    defaultFgColor:
      - "#F7F4F2"
    searchingActiveBorderColor:
      - "#F0E68C"

  authorColors:
    "*": "#F0E68C"
update:
  method: never
os:
  editPreset: "nvim"
  edit: "~/.config/lazygit/lazygit-edit {{filename}}"
  editAtLine: "~/.config/lazygit/lazygit-edit {{filename}} {{line}}"
  editAtLineAndWait: "~/.config/lazygit/lazygit-edit {{filename}} {{line}}"
customCommands:
  - key: '<ctrl+g>'
    context: files
    command: 'mergiraf solve {{ .SelectedFile.Name | quote }}'
    description: 'Resolve with Mergiraf'
disableStartupPopups: true
notARepository: skip
