# hypr/.config/hypr/hyprpaper.conf
#
#    ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗ 
#    ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
#    ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
#    ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
#    ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
#    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
#

# ──────────────────────────────────────────────────────────────────────────── #
# !-- Config
# ──────────────────────────────────────────────────────────────────────────── #

splash = false
ipc = true

# ──────────────────────────────────────────────────────────────────────────── #
# !-- Wallpapers
# ──────────────────────────────────────────────────────────────────────────── #

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/Pixel Art/wallhaven-qz8ved.jpg
}

wallpaper {
    monitor = eDP-2
    path = ~/Pictures/Wallpapers/Pixel Art/wallhaven-qz8ved.jpg
}

wallpaper {
    monitor = DP-8
    path = ~/Pictures/Wallpapers/Pixel Art/wallhaven-28r5eg.png
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpapers/Pixel Art/wallhaven-57wql7.png
}
