# hypr/.config/hypr/hyprpaper.conf
#
#    ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗
#    ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
#    ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
#    ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
#    ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
#    ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
#

# ──────────────────────────────────────────────────────────────────────────── #
# !-- Config
# ──────────────────────────────────────────────────────────────────────────── #

splash = false
ipc = true

# ──────────────────────────────────────────────────────────────────────────── #
# !-- Wallpapers
# ──────────────────────────────────────────────────────────────────────────── #

wallpaper {
    monitor =
    path = ~/Pictures/Wallpapers/Pixel Art/wallhaven-9d5zm8.png
}

wallpaper {
    monitor = eDP-2
    path = ~/Pictures/Wallpapers/Pixel Art/GhostCastleNight.webp
}

wallpaper {
    monitor = DP-8
    path = ~/Pictures/Wallpapers/Pixel Art/pc-98-cityscapes-v0-lxav5naclx0e1.webp
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpapers/Pixel Art/RiverPort.webp
}
