-- hypr/.config/hypr/theme/lib/generators/kitty.lua
-- Kitty terminal theme generator

local Utils = require("lib.utils")
local Palette = require("lib.palette")
local BaseGenerator = require("lib.generators.base")

local KittyGenerator = setmetatable({}, { __index = BaseGenerator })
KittyGenerator.__index = KittyGenerator

function KittyGenerator:new()
	local obj = BaseGenerator:new()
	setmetatable(obj, self)
	return obj
end

function KittyGenerator:generate(palette, output_dir, palette_name)
	local home = os.getenv("HOME")
	local kitty_config_dir = home .. "/.config/kitty"
	local kitty_themes_dir = kitty_config_dir .. "/themes"

	-- Convert palette name format (e.g., "Oasis Lagoon Dark" -> "oasis_lagoon_dark")
	local theme_filename = palette_name:lower():gsub("%s+", "_") .. ".conf"
	local existing_theme_path = kitty_themes_dir .. "/" .. theme_filename

	-- Check if theme already exists in kitty themes directory
	local theme_file = io.open(existing_theme_path, "r")
	if theme_file then
		theme_file:close()
		print("✓ Kitty: Using existing theme: " .. theme_filename)
		self:setup_auto_conf(kitty_config_dir, kitty_themes_dir, theme_filename, palette_name)
		Utils.write_file(output_dir .. "/kitty-theme-name.txt", theme_filename)
		return true
	end

	-- Theme doesn't exist, generate it
	print("✓ Kitty: Generating new theme: " .. theme_filename)
	local content = self:build_theme_content(palette, theme_filename, palette_name)
	local generated_path = kitty_themes_dir .. "/" .. theme_filename

	if Utils.write_file(generated_path, content) then
		self:setup_auto_conf(kitty_config_dir, kitty_themes_dir, theme_filename, palette_name)
		Utils.write_file(output_dir .. "/kitty-theme-name.txt", theme_filename)
		return true
	end

	return false
end

function KittyGenerator:setup_auto_conf(kitty_config_dir, kitty_themes_dir, theme_filename, palette_name)
	-- Create dark-theme.auto.conf
	local auto_conf_content = string.format("include %s/%s\n", kitty_themes_dir, theme_filename)
	Utils.write_file(kitty_config_dir .. "/dark-theme.auto.conf", auto_conf_content)

	-- If this is a dark theme, search for corresponding light theme
	if palette_name:lower():match("dark") then
		local base_name = palette_name:gsub("[Dd]ark", "")
		local search_pattern = base_name:lower():gsub("%s+", "_") .. "light*.conf"
		local find_cmd = string.format('ls %s/%s 2>/dev/null | head -1', kitty_themes_dir, search_pattern)
		local handle = Utils.popen_assert(find_cmd)
		local light_theme_path = handle:read("*line")
		handle:close()

		if light_theme_path and light_theme_path ~= "" then
			local light_filename = light_theme_path:match("([^/]+)$")
			local light_auto_conf = string.format("include %s/%s\n", kitty_themes_dir, light_filename)
			Utils.write_file(kitty_config_dir .. "/light-theme.auto.conf", light_auto_conf)
			print("✓ Kitty: Using light theme: " .. light_filename)
		end
	end
end

function KittyGenerator:build_theme_content(palette, theme_filename, palette_name)
	return string.format(
		[[# kitty/themes/%s
# Generated by theme/main.lua
## name: %s
## author: theme

# ANSI Color Palette (0-15)
color0  %s
color1  %s
color2  %s
color3  %s
color4  %s
color5  %s
color6  %s
color7  %s
color8  %s
color9  %s
color10 %s
color11 %s
color12 %s
color13 %s
color14 %s
color15 %s

# Core Colors
foreground               %s
background               %s

# Selection
selection_background     %s
selection_foreground     %s

# Cursor
cursor                   %s
cursor_text_color        %s

# Borders (panes)
active_border_color      %s
inactive_border_color    %s

# Tabs
active_tab_foreground    %s
active_tab_background    %s
inactive_tab_foreground  %s
inactive_tab_background  %s
]],
		theme_filename,
		palette_name,
		-- ANSI colors 0-7
		Palette.ensure_hex(palette.color0 or palette.black),
		Palette.ensure_hex(palette.color1 or palette.red),
		Palette.ensure_hex(palette.color2 or palette.green),
		Palette.ensure_hex(palette.color3 or palette.yellow),
		Palette.ensure_hex(palette.color4 or palette.blue),
		Palette.ensure_hex(palette.color5 or palette.magenta),
		Palette.ensure_hex(palette.color6 or palette.cyan),
		Palette.ensure_hex(palette.color7 or palette.white),
		-- ANSI bright colors 8-15
		Palette.ensure_hex(palette.color8 or palette.bright_black),
		Palette.ensure_hex(palette.color9 or palette.bright_red),
		Palette.ensure_hex(palette.color10 or palette.bright_green),
		Palette.ensure_hex(palette.color11 or palette.bright_yellow),
		Palette.ensure_hex(palette.color12 or palette.bright_blue),
		Palette.ensure_hex(palette.color13 or palette.bright_magenta),
		Palette.ensure_hex(palette.color14 or palette.bright_cyan),
		Palette.ensure_hex(palette.color15 or palette.bright_white),
		-- Core colors
		Palette.ensure_hex(palette.fg_core),
		Palette.ensure_hex(palette.bg_core),
		-- Selection
		Palette.ensure_hex(palette.bg_surface),
		Palette.ensure_hex(palette.fg_core),
		-- Cursor
		Palette.ensure_hex(palette.yellow),
		Palette.ensure_hex(palette.bg_core),
		-- Borders
		Palette.ensure_hex(palette.theme_primary),
		Palette.ensure_hex(palette.bg_mantle),
		-- Tabs
		Palette.ensure_hex(palette.bg_core),
		Palette.ensure_hex(palette.yellow),
		Palette.ensure_hex(palette.fg_muted),
		Palette.ensure_hex(palette.bg_mantle)
	)
end

return KittyGenerator
