-- hypr/.config/hypr/theme/lib/generators/rofi.lua
-- Rofi theme generator

local Utils = require("lib.utils")
local BaseGenerator = require("lib.generators.base")

local RofiGenerator = setmetatable({}, { __index = BaseGenerator })
RofiGenerator.__index = RofiGenerator

function RofiGenerator:new()
	local obj = BaseGenerator:new()
	setmetatable(obj, self)
	return obj
end

function RofiGenerator:generate(palette, output_dir, palette_name)
	local content = string.format(
		[[/**
 * rofi/.config/rofi/theme-colors.rasi
 * Generated by theme/main.lua
 * DO NOT EDIT MANUALLY - regenerate with: lua ~/.config/hypr/theme/main.lua
 **/

* {
    background:     %s;
    background-alt: %s;
    foreground:     %s;
    selected:       %s;
    active:         %s;
    urgent:         %s;
}
]],
		Utils.ensure_hex(palette.bg_core) .. "FF",
		Utils.ensure_hex(palette.bg_surface) .. "FF",
		Utils.ensure_hex(palette.fg_core) .. "FF",
		Utils.ensure_hex(palette.theme_primary) .. "FF",
		Utils.ensure_hex(palette.yellow) .. "FF",
		Utils.ensure_hex(palette.error) .. "FF"
	)

	local output_path = output_dir .. "/rofi-theme.rasi"
	return self:write_output(output_path, content)
end

return RofiGenerator
