-- hypr/.config/hypr/theme/lib/generators/waybar.lua
-- Waybar CSS theme generator

local Utils = require("lib.utils")
local Palette = require("lib.palette")
local BaseGenerator = require("lib.generators.base")

local WaybarGenerator = setmetatable({}, { __index = BaseGenerator })
WaybarGenerator.__index = WaybarGenerator

function WaybarGenerator:new()
	local obj = BaseGenerator:new()
	setmetatable(obj, self)
	return obj
end

function WaybarGenerator:generate(palette, output_dir, palette_name)
	local content = string.format(
		[[/* waybar/.config/waybar/theme-colors.css */
/* Generated by theme/main.lua */
/* DO NOT EDIT MANUALLY - regenerate with: lua ~/.config/hypr/theme/main.lua */

/* Backgrounds */
@define-color bg_core %s;
@define-color bg_mantle %s;
@define-color bg_shadow %s;
@define-color bg_surface %s;

/* Foregrounds */
@define-color fg_core %s;
@define-color fg_strong %s;
@define-color fg_muted %s;
@define-color fg_dim %s;

/* Accents */
@define-color primary %s;
@define-color secondary %s;
@define-color accent %s;
@define-color yellow %s;

/* Status Colors */
@define-color error %s;
@define-color warning %s;
@define-color info %s;
@define-color hint %s;
@define-color ok %s;

/* ANSI Colors (for reference) */
@define-color red %s;
@define-color green %s;
@define-color blue %s;
@define-color cyan %s;
@define-color magenta %s;
]],
		Palette.ensure_hex(palette.bg_core),
		Palette.ensure_hex(palette.bg_mantle),
		Palette.ensure_hex(palette.bg_shadow),
		Palette.ensure_hex(palette.bg_surface),
		Palette.ensure_hex(palette.fg_core),
		Palette.ensure_hex(palette.fg_strong),
		Palette.ensure_hex(palette.fg_muted),
		Palette.ensure_hex(palette.fg_dim),
		Palette.ensure_hex(palette.theme_primary),
		Palette.ensure_hex(palette.theme_secondary),
		Palette.ensure_hex(palette.theme_accent),
		Palette.ensure_hex(palette.yellow),
		Palette.ensure_hex(palette.error),
		Palette.ensure_hex(palette.warning),
		Palette.ensure_hex(palette.info),
		Palette.ensure_hex(palette.hint),
		Palette.ensure_hex(palette.ok),
		Palette.ensure_hex(palette.red),
		Palette.ensure_hex(palette.green),
		Palette.ensure_hex(palette.blue),
		Palette.ensure_hex(palette.cyan),
		Palette.ensure_hex(palette.magenta)
	)

	local output_path = output_dir .. "/waybar-theme.css"
	return self:write_output(output_path, content)
end

return WaybarGenerator
