# yazi/.config/yazi/keymap.toml
[mgr]
prepend_keymap = [
  # Utils
  { on = "?", run = "help", desc = "Open help" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },

  # Toggles
  { on = ["T", "f"], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
  { on = ["T", "p"], run = "plugin toggle-pane min-preview", desc = "Toggle the preview pane" },

  # Relative motions
  { on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps" },

  # Go to...
  { on = [ "g", "/", ], run = "cd /", desc = "Go to /" },
  { on = [ "g", "C", ], run = "cd /home/roberth/Documents/Clients/", desc = "Go to Clients" },
  { on = [ "g", "D", ], run = "cd /home/roberth/Documents/", desc = "Go to Documents" },
  { on = [ "g", "G", ], run = "cd /data/Games/Steam/steamapps/common/", desc = "Go to Steam Games" },
  { on = [ "g", "H", ], run = "cd /home/roberth/.config/hypr/", desc = "Go to ~/.config/hypr" },
  { on = [ "g", "L", ], run = "cd /home/roberth/.local/", desc = "Go to ~/.local" },
  { on = [ "g", "M", ], run = "plugin sshfs -- jump", desc = "Jump to mount" },
  { on = [ "g", "S", ], run = "cd /home/roberth/.local/share/Steam/steamapps/compatdata/", desc = "Go to Steam Data" },
  { on = [ "g", "T", ], run = "cd /tmp", desc = "Go to /tmp" },
  { on = [ "g", "X", ], run = "cd /home/roberth/dotfiles-private/", desc = "Go to private dotfiles" },
  { on = [ "g", "F", ], run = "cd ~/.local/share/fonts/", desc = "Go to fonts" },
  { on = [ "g", "f", ], run = "cd /data/", desc = "Go to Media Files" },
  { on = [ "g", "l", ], run = "shell 'yazi-lazygit-cd' --block --confirm=false", desc = "Lazygit" },
  { on = [ "g", "m", ], run = "cd /run/media/$USER/", desc = "Go to media (usb)" },
  { on = [ "g", "n", ], run = "cd /home/roberth/Documents/Notes/", desc = "Go to Notes" },
  { on = [ "g", "p", ], run = "cd /home/roberth/Pictures/", desc = "Go to Pictures" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"', desc = "Go to git root" },
  { on = [ "g", "s", ], run = "cd /home/roberth/.local/share/Steam/steamapps/common/", desc = "Go to Steam Apps" },
  { on = [ "g", "u", ], run = "cd /home/roberth/Development/", desc = "Go to Development" },
  { on = [ "g", "v", ], run = "cd /home/roberth/Videos/", desc = "Go to Videos" },
  { on = [ "g", "x", ], run = "cd /home/roberth/dotfiles/", desc = "Go to dotfiles" },
  { on = [ "g", "y", ], run = "cd /home/roberth/.config/yazi/", desc = "Go to yazi config" },
  { on = [ "g", "z", ], run = "cd /home/roberth/.local/state/yazi", desc = "Go to Yazi debug log" },

  # In...
  { on = ["i", "d"], run = "shell -- dolphin .", desc = "Open in Dolphin" },
  { on = ["i", "i"], run = 'shell --block -- stat %h; echo; file %h; echo; read -n 1 -s -r -p "Press any key..."', desc = "Inspect file" },
  { on = ["i", "r"], run = "shell --block -- %h", desc = "Run executable" },
  { on = ["i", "R"], run = "shell --orphan -- %h", desc = "Run executable detached" },


  # Mount
  { on = [ "M", "m", ], run = "plugin mount", desc = "Open Mount Options" },
  { on = [ "M", "s", ], run = "plugin sshfs -- menu", desc = "Open SSHFS Options" },

  # Change
  { on = [ "c", "m", ], run = "plugin chmod", desc = "Chmod on selected files" },

  # Restore
  { on = [ "u", ], run = "plugin restore", desc = "Restore last deleted files/folders" },

  # Trash
  { on = [ "g", "t", ], run = "plugin recycle-bin open", desc = "Go to Trash" },
  { on = [ "R" ], run = "plugin recycle-bin", desc = "Open Recycle Bin Menu" },

  # Admin
  { on = ["A", "o"], run = "shell --block -- sudoedit %h", desc = "Sudoedit File"},
  { on = ["A", "y"], run = "shell --block -- sudo yazi %d", desc = "Sudo Yazi"},
  { on = ["A", "x"], run = "shell -- sudo chmod +x %h", desc = "Sudo chmod +x" },
  { on = ["A", "m"], run = 'shell --block -- printf "chmod: "; read mode; sudo chmod "$mode" %h', desc = "Sudo chmod" },
  { on = ["A", "c"], run = 'shell --block -- ls -l %h; printf "owner[:group]: "; read owner; [ -n "$owner" ] && sudo chown "$owner" %h', desc = "Sudo chown" },

  # Zip Archive...
  { on = ["z", "u"], run = "shell --block -- 7z x %h", desc = "Unzip archive" },
  { on = ["z", "z"], run = 'shell -- file=%h; dir="$(dirname "$file")"; base="$(basename "$file")"; tar -czf "$base.tar.gz" -C "$dir" "$base"', desc = "Compress tar.gz" },
]
