# yazi/.config/yazi/yazi.toml
[opener]
csv = [
  { run = 'nless "$@"', block = true, desc = "Nless", for = "unix" },
  { run = '/usr/bin/nvim "$@"', block = true, desc = "NeoVim", for = "unix" },
  { run = 'libreoffice --calc "$@"', block = false, desc = "Libreoffice", for = "unix" },
]
edit = [
  { run = '/usr/bin/nvim "$@"', block = true, desc = "NeoVim", for = "unix" },
  { run = 'vim "$@"', block = true, desc = "Vim", for = "unix" },
  { run = 'nless "$@"', block = true, desc = "Nless", for = "unix" },
  { run = 'libreoffice --calc "$@"', block = false, desc = "Libreoffice", for = "unix" },
]
image-edit = [
  { run = 'gimp "$@"', block = true, desc = "Gimp", for = "unix" },
  { run = 'inkscape "$@"', block = true, desc = "Inkscape", for = "unix" },
  { run = '/usr/bin/nvim "$@"', block = true, desc = "NeoVim", for = "unix" },
]
install-rpm = [
  { run = "sh -lc 'sudo dnf -y install \"$1\"' -- \"$@\"", block = true, desc = "DNF Install (sudo)", for = "unix" },
]
video = [
  { run = 'vlc "$@"', orphan = true, desc = "VLC", for = "unix" },
  { run = 'kdenlive "$@"', orphan = true, desc = "Kdenlive", for = "unix" },
]
pdf = [{ run = 'zathura "$@"', orphan = true, desc = "Zathura", for = "unix" }]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
  { run = '/usr/bin/nvim "$@"', block = true, desc = "NeoVim", for = "unix" },
  { run = 'vim "$@"', block = true, desc = "Vim", for = "unix" },
  { run = 'gimp "$@"', block = true, desc = "Gimp", for = "unix" },
  { run = 'inkscape "$@"', block = true, desc = "Inkscape", for = "unix" },
]

[open]
prepend_rules = [
  { url = "*.csv", use = "csv" },
  { mime = "text/csv", use = "csv" },
  { url = "*.rpm", use = "install-rpm" },
  { mime = "image/*", use = "image-edit" },
  { mime = "video/*", use = "video" },
  { mime = "application/pdf", use = "pdf" },
]

[plugin]
prepend_preloaders = [
  # Do not preload files in mounted locations:
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },

  # For mounted location for hard disk/drive
  { url = "/run/media/*/**/*", run = "noop" },
  { url = "~/mnt/*", run = "noop" },
  #... the rest of preloaders
]
prepend_previewers = [
  # Allow to preview folder.
  { url = "*/", run = "folder", sync = true },

  # Do not preview files in mounted locations (uncomment to except text file):
  # { mime = "{text/*,application/x-subrip}", run = "code" },
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },
  { url = "~/mnt/*", run = "noop" },

  # For mounted hard disk.
  { url = "/run/media/*/**/*", run = "noop" },
]
prepend_fetchers = [
  { group = "git", url = "*", run = "git" },
  { group = "git", url = "*/", run = "git" },
]

[mgr]
linemode = "steam_appid"
