#!/bin/bash
# hypr/.config/hypr/scripts/generate-plugins-config.sh
# Combines all plugin configs from plugins/ into a single file

PLUGIN_DIR="$HOME/.config/hypr/plugins"
OUTPUT_FILE="$HOME/.config/hypr/config/plugins.conf"

# Ensure plugins directory exists
if [ ! -d "$PLUGIN_DIR" ]; then
  mkdir -p "$PLUGIN_DIR"
fi

# Generate combined configuration
{
  cat <<'EOF'
# Auto-generated combined plugin configuration
# This file is generated by scripts/generate-plugins-config.sh
# DO NOT EDIT MANUALLY - changes will be overwritten

EOF

  # Loop through all .conf files in plugins/ directory (sorted)
  for plugin_conf in "$PLUGIN_DIR"/*.conf; do
    if [ -f "$plugin_conf" ]; then
      echo "# ────────────────────────────────────────────────────────"
      echo "# From: $(basename "$plugin_conf")"
      echo "# ────────────────────────────────────────────────────────"
      cat "$plugin_conf"
      echo ""
    fi
  done
} >"$OUTPUT_FILE"

logger -t "hypr-plugins" "Combined plugin configuration generated: $OUTPUT_FILE"
