#!/usr/bin/env bash
# hypr/.config/hypr/scripts/power.sh
# Applies the power state file: idle timeouts, power profile, lid and power button actions.
# Usage: power.sh watch|apply|idle|lid|button

state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/hypr"
state="$state_dir/power.json"
tracked_idle="$HOME/.config/hypr/hypridle.conf"
generated_idle="$state_dir/hypridle.conf"
runtime="${XDG_RUNTIME_DIR:-/tmp}"
inhibit_tag="hypr-power-inhibit"

cfg() {
  local value
  value=$(jq -r --arg k "$1" '.[$k] // empty' "$state" 2>/dev/null)
  echo "${value:-$2}"
}

on_ac() {
  local dir type has_battery=0
  for dir in /sys/class/power_supply/*; do
    type=$(cat "$dir/type" 2>/dev/null)
    if [ "$type" = Battery ]; then
      has_battery=1
    elif [ "$type" != UPS ] && [ "$(cat "$dir/online" 2>/dev/null)" = 1 ]; then
      return 0
    fi
  done
  [ "$has_battery" = 0 ]
}

source_name() {
  if on_ac; then echo ac; else echo battery; fi
}

idle_conf() {
  if [ -f "$state" ]; then echo "$generated_idle"; else echo "$tracked_idle"; fi
}

listener() {
  local timeout=$1 on_timeout=$2 on_resume=${3:-}
  [ "$timeout" -gt 0 ] 2>/dev/null || return 0
  printf '\nlistener {\n    timeout = %s\n    on-timeout = %s\n' "$timeout" "$on_timeout"
  [ -n "$on_resume" ] && printf '    on-resume = %s\n' "$on_resume"
  printf '}\n'
}

gen_idle() {
  local src tmp
  [ -f "$state" ] || return 1
  src=$(source_name)
  mkdir -p "$state_dir"
  tmp=$(mktemp "$state_dir/hypridle.XXXXXX")
  {
    printf '# Generated by power.sh from power.json; edit the Settings panel instead.\n\n'
    awk '/^general \{/,/^\}/' "$tracked_idle"
    listener "$(cfg "dim_$src" 150)" "brightnessctl -s set 10" "brightnessctl -r"
    listener "$(cfg "lock_$src" 300)" "loginctl lock-session"
    listener "$(cfg "screen_off_$src" 0)" "hyprctl dispatch 'hl.dsp.dpms({ action = \"disable\" })'" "hyprctl dispatch 'hl.dsp.dpms({ action = \"enable\" })' && brightnessctl -r"
    listener "$(cfg "suspend_$src" 0)" "systemctl suspend"
  } >"$tmp"
  if cmp -s "$tmp" "$generated_idle"; then
    rm -f "$tmp"
    return 1
  fi
  mv "$tmp" "$generated_idle"
}

start_idle() {
  setsid -f hypridle -c "$(idle_conf)" >/dev/null 2>&1 9>&-
}

idle() {
  gen_idle
  exec hypridle -c "$(idle_conf)"
}

apply_idle() {
  if gen_idle && pgrep -x hypridle >/dev/null; then
    pkill -x hypridle
    start_idle
  fi
}

apply_profile() {
  local profile
  profile=$(cfg "profile_$(source_name)" keep)
  [ "$profile" = keep ] && return 0
  powerprofilesctl set "$profile" >/dev/null 2>&1
}

inhibiting() {
  pgrep -f -- "$inhibit_tag" >/dev/null
}

apply_inhibitor() {
  local want=0
  [ "$(cfg lid_ac suspend)" != suspend ] && want=1
  [ "$(cfg lid_battery suspend)" != suspend ] && want=1
  [ "$(cfg power_button poweroff)" != poweroff ] && want=1
  if [ "$want" = 1 ] && ! inhibiting; then
    setsid -f systemd-inhibit --what=handle-lid-switch:handle-power-key --who="$inhibit_tag" \
      --why="Lid and power button handled by Hyprland" --mode=block \
      bash -c 'exec -a hypr-power-inhibit sleep infinity' >/dev/null 2>&1 9>&-
  elif [ "$want" = 0 ] && inhibiting; then
    pkill -f -- "$inhibit_tag"
  fi
}

apply() {
  [ -f "$state" ] || return 0
  apply_idle
  apply_profile
  apply_inhibitor
}

do_action() {
  case "$1" in
  suspend) systemctl suspend ;;
  lock) "$HOME/.config/hypr/scripts/lock-screen.sh" ;;
  poweroff) systemctl poweroff ;;
  esac
}

watch() {
  local last now
  exec 9>"$runtime/hypr-power-watch.lock"
  flock -n 9 || exit 0
  apply
  pgrep -x hypridle >/dev/null || start_idle
  last=$(source_name)
  udevadm monitor --udev --subsystem-match=power_supply | while read -r _; do
    now=$(source_name)
    [ "$now" = "$last" ] && continue
    last=$now
    apply
  done
}

case "${1:-}" in
watch) watch ;;
apply) apply ;;
idle) idle ;;
lid) inhibiting && do_action "$(cfg "lid_$(source_name)" suspend)" ;;
button) inhibiting && do_action "$(cfg power_button poweroff)" ;;
*)
  echo "usage: power.sh watch|apply|idle|lid|button" >&2
  exit 2
  ;;
esac
