[CORE]
stow
git
zsh
neovim
tmux
curl
wget

[DESKTOP]
wtype
kitty
starship
yazi
fastfetch
hyprland
hyprpaper
hypridle
hyprlock
hyprpicker
hyprpolkitagent
xdg-desktop-portal-hyprland
xdg-desktop-portal-gtk
papirus-icon-theme
qt5-qtwayland
qt6-qtwayland
waybar
rofi
swaync
wl-clipboard
cliphist
grim
slurp
udiskie
brightnessctl
pamixer
playerctl
cava

[GRAPHICS]
mesa-dri-drivers
mesa-vulkan-drivers
glx-utils
vulkan-tools
libva-utils

[SYSTEM]
NetworkManager
bluez
openssh
lua
ruby
python3
keyd
greetd
tuigreet
fzf
ripgrep
fd-find
jq
less
man-db
unzip
xdg-user-dirs
xdg-utils
luarocks

[CLI]
bat
lsd
tree
zoxide
tldr
btop
htop
aria2
rclone
rsync
yt-dlp
git-delta
lazygit
archivemount
trash-cli
zip
7zip
duf
du-dust

[DEV]
gh
clang
cmake
docker-cli
docker-buildx
docker-compose
pandoc-cli
pipx
ShellCheck
shfmt

[FONTS]
google-noto-fonts-common
google-noto-emoji-fonts
google-noto-sans-cjk-fonts
liberation-fonts-all
dejavu-fonts-all

[MEDIA]
mpv
vlc
ffmpeg-free
gimp
inkscape
bottles

[AUDIO]
pipewire
pipewire-alsa
pipewire-pulseaudio
pipewire-jack-audio-connection-kit
wireplumber
pavucontrol
easyeffects

[MANUAL]
# wl-kbptr — no Fedora package; build from source: https://github.com/moverest/wl-kbptr
