# Flatpak apps installed from Flathub
# Sections: [CORE] always installed, [GAMING]/[GAMES]/[SECURITY] prompt user

[CORE]
eu.betterbird.Betterbird

[GAMING]
com.vysp3r.ProtonPlus

[GAMES]
org.srb2.SRB2

[SECURITY]
com.bitwarden.desktop
