[CORE]
# shell
bash
zsh

# editor
neovim
vim

# terminal
tmux
kitty
starship
fastfetch

# desktop
hypr
waybar
rofi
swaync
gtk
hyprland-preview-share-picker

# tools
yazi
lint
easyeffects
satty
wl-kbptr
zathura

# system
git
topgrade
systemd
voxtype

[OPTIONAL]
# browsers
qutebrowser
tridactyl

# system
xdg-desktop-portal

# tools
intelli-shell

# news
newsboat

# mail
thunderbird

# media
cliamp
wallpapers

# ai
claude
codex
qwen
gemini
