[CORE]
# shell
bash
zsh

# editor
vim

# terminal
tmux
kitty
starship
fastfetch

# desktop
hypr
quickshell
rofi
gtk
hyprland-preview-share-picker

# tools
yazi
lint
easyeffects
satty
wl-kbptr
zathura

# system
git
topgrade
systemd
voxtype

[OPTIONAL]
# browsers
qutebrowser
tridactyl

# system
xdg-desktop-portal

# tools
intelli-shell

# news
newsboat

# mail
thunderbird

# media
cliamp
wallpapers

# ai
claude
codex
qwen
gemini

[SERVER]
bash
zsh
vim
tmux
starship
fastfetch
yazi
git
lazygit
lint
topgrade
