[CORE]
# shell
bash
zsh

# editor
neovim
vim

# terminal
tmux
kitty
starship
fastfetch

# desktop
hypr
waybar
rofi
swaync

# tools
yazi
lint
easyeffects
satty
wl-kbptr

# system
git
keyd
voxtype

[OPTIONAL]
# browsers
qutebrowser
tridactyl

# system
xdg-desktop-portal

# tools
intelli-shell

# news
newsboat

# media
cliamp

# ai
claude
codex
qwen
gemini
